### ISSUE TITLE
rebuild_userChrome.uc.js for multiple window not work

### ISSUE THREAD

**Issue by ArkadiuszMichalski** [xiaoxiaoflood/firefox-scripts#10]
Step to reproduce:
1. Open browser with that script (let say it's window A).
2. Open next window B.
3. Close window A.
3. From window B open next window C.

and bah, userChromeJSManager not work.

**Comment by xiaoxiaoflood** [comment]
Thank you for reporting, this should be fixed now, please update your [rebuild_userChrome.uc.js](https://github.com/xiaoxiaoflood/firefox-scripts/blob/master/chrome/rebuild_userChrome.uc.js).

edaca64
