### ISSUE TITLE
Mouse Gesture not working properly (open image)

### ISSUE THREAD

**Issue by Mitezuss** [xiaoxiaoflood/firefox-scripts#100]
Can not open the images a new tab on the site: jaidefinichon.com

But it is possible with the old version of the script

**Comment by xiaoxiaoflood** [comment]
It works for me. Right-click the image, hold, move right, release → image opens in new tab.

**Comment by Mitezuss** [comment]
@xiaoxiaoflood 

So rare =/

On my browser, the last version, open (in any image):
https://static.tumblr.com/tt9qf5k/2BGm9l2tx/brillito_oe_zi_20.png

should open (for example):
https://jaidefinichon.com/wp-content/uploads/2021/11/tumblr_75733dbae4a2d4e667eac47d0c333b44_2c998a1b_540.jpg


But with the old version work fine =/ (https://github.com/xiaoxiaoflood/firefox-scripts/blob/317301880a3b30240838fa6031aa6bbc70835961/chrome/mouseGestures.uc.js)

Anyway, thank for reply

**Comment by xiaoxiaoflood** [comment]
Thanks for reporting. It's working for me, but now I realized that I probably forgot to update the script in the repo. It's working for me and not for you because my version is different. Now it should be fixed.

**Comment by Mitezuss** [comment]
Yes, now is working.
