### ISSUE TITLE
Not an Issue but Request: enable maximize/minimize on status-bar.uc.js ?

### ISSUE THREAD

**Issue by mimteatr** [xiaoxiaoflood/firefox-scripts#101]
Hello,

Sorry if this is not the right place, I don't know where to address you and if it can be done...

Do you have a way to enable the Maximize/Minimize the window by double-clicking (or right-clicking, etc) on the 
status-bar.uc.js ?

Thanks in advance!

**Comment by xiaoxiaoflood** [comment]
win.statusbar.node.addEventListener('dblclick', win.minimize.bind(win));

You can append this in line 88. You can replace `minimize` by `restore` or `maximize`. If I understood correctly what you meant...

**Comment by mimteatr** [comment]
Yes you did understand me and it works, partially... I'll explain myself cause now I also understand better what I want.

I don't actually need the minimize option since I'm using your `minMaxCloseButton.uc.js` which I place on the extreme left of the status and from there I can; of course minimize or close FF.

I would like that if the window is maximized, clicking on the status bar will resize the windows to a smaller size, whatever it is that I have resized sometime and clicking back on the status bar will then maximize/restore it to maximized.

Right now I see that with your code is possible only one choice,; is there an option for what I want?

While on it, is it also possible to enable to drag the window with a single click on the status bar?

**Comment by xiaoxiaoflood** [comment]
Restore if maximized, maximize if restored:
```js
    win.statusbar.node.addEventListener('dblclick', () => {
      if (win.document.getElementById('main-window').getAttribute('sizemode') == 'maximized')
        win.restore();
      else
        win.maximize();
    });
```

Regarding dragging the window, it may be possible but I don't know how.

**Comment by mimteatr** [comment]
Wonderful, thank you!

Should  I leave this open in case you find a solution for dragging? It's up to you, you've already helped a lot 🙏🌹

**Comment by mimteatr** [comment]
Hello,

In case it interests you, if someone else asks, disabling the code above and adding `#status-text{ -moz-window-dragging: drag !important }` to userChrome.css solves both requests (dragging & resizing).

Cheers!

**Comment by xiaoxiaoflood** [comment]
Good to know, thanks for sharing. I'll add it to my personal status-bar, but not to the published script because the old status-bar didn't have this *feature* so other users may find it unwanted.

P.S. you don't need to edit userChrome.css, you can just append `-moz-window-dragging: drag;` here
https://github.com/xiaoxiaoflood/firefox-scripts/blob/d609a1d03d9a78e01668b4b5528cfbc9a001788a/chrome/status-bar.uc.js#L136-L141

**Comment by mimteatr** [comment]
Great, thanks!
