### ISSUE TITLE
DownThemAll Unnoficial for Fx 57+ working in Waterfox G4?

### ISSUE THREAD

**Issue by LeeBinder** [xiaoxiaoflood/firefox-scripts#104]
Hi. In [WF G4 4.0.3](https://www.waterfox.net/download) in macOS, after successfully installing [xiaoxiaoflood/DownThemAll](https://github.com/xiaoxiaoflood/firefox-scripts/tree/master/extensions/DownThemAll), clicking onto the Manager icon in the toolbar,  I'm getting

  ```javascript
XML Parsing Error: undefined entity
Location: chrome://dta-platform/content/manager.xhtml
Line Number 62, Column 9:
        <key id="key_minimizeWindow"
--------^
  ```

The DownThemAll button in the toolbar at least brings up the DownThemAll window, so something is working correctly.

Installed fx-folder.zip and utils.zip as per [firefox-scripts#instructions](https://github.com/xiaoxiaoflood/firefox-scripts#instructions):

<details>
  <summary>click to expand</summary> 

    1. Download https://raw.githubusercontent.com/xiaoxiaoflood/firefox-scripts/master/fx-folder.zip (source: https://github.com/xiaoxiaoflood/firefox-scripts#instructions)
    extract its content into:

    - Windows: Firefox installation folder - usually C:\Program Files\Mozilla Firefox
    
    - macOS: Firefox App (usually in /Applications):
    /Applications/Firefox.app/Contents/Resources
    
    - Linux: see https://github.com/xiaoxiaoflood/firefox-scripts/issues/8#issuecomment-467619800

	2. Click Firefox' menu button (☰) -> Help -> More troubleshooting information or simply open about:support. Find "Profile Folder", then click "Open folder". In there, create a new folder called chrome.
	
	3. Download one of the files below and extract its content in chrome folder.

	I'm only interested in extensions -> https://raw.githubusercontent.com/xiaoxiaoflood/firefox-scripts/master/utils_extensions_only.zip

	I'm interested in both scripts and extensions -> https://raw.githubusercontent.com/xiaoxiaoflood/firefox-scripts/master/utils.zip

	4. Open about:support and click "Clear startup cache…" to force Firefox to load userChromeJS on the next startup.
	
	5. in about:config , set xpinstall.whitelist.required to false (if it isn't set to false yet)

	6. Restart Firefox.
 
</details>

Other legacy extensions like Tab Mix Plus work fine.

Also reproduced this issue in a brand new profile from scratch with nothing else installed.

Any ideas? Anybody else running [xiaoxiaoflood/DownThemAll](https://github.com/xiaoxiaoflood/firefox-scripts/tree/master/extensions/DownThemAll) in WF G4?

**Comment by xiaoxiaoflood** [comment]
I don't have an Apple device here to test, but this doesn't seem to be related to Waterfox, it's a leftover from some Firefox update that I didn't notice because I only test my extensions on Windows 10.

In addition to the reported issue, at this point I fear that DTA! layout/theme may be very compromised on non-W10 OS for the same reason.

P.S. things in this page are targeted to current Firefox Developer Edition, I don't provide support to any other version including Firefox ESR (Waterfox Current is based on Fx ESR). But I guess this is not the cause of the reported issue, it should also affect DevEd for macOS users.

**Comment by LeeBinder** [comment]
OK thanks @xiaoxiaoflood for the behind-the-scenes insights. Just tested: the error is the same in regular release-channel Firefox macOS. Usually WFx current has proven to be more compatible with your Extensions here than FFx, but not in this case.

I think @nmaier is exclusively focused on DTA WE (which I've been using in WFx and FFx) and can't/ won't do anything about this, and I guess we can close this issue.

**Comment by xiaoxiaoflood** [comment]
I made some changes. If you can, please test it on your macOS. Download the file below, rename it from .zip to .xpi and install the addon.

[dta.zip](https://github.com/xiaoxiaoflood/firefox-scripts/files/7585477/dta.zip)

If it works, I'll release this version as an update.

> Usually WFx current has proven to be more compatible with your Extensions here than FFx

Actually it's the opposite. I use Firefox, not Waterfox. I use Firefox Developer Edition which is the same as Firefox Beta, so 1 version ahead than *normal* Firefox. Waterfox uses ESR that can be more than a year behind Developer Edition.
Current Firefox: 94
Current DevEd: 95
Current Waterfox: 91

May 2022:
Firefox: 101
DevEd: 102
Waterfox: still 91

**Comment by LeeBinder** [comment]
Thank you xiaoxiaoflood. Result, both in latest WFx and FFx, new virgin profile, again first removed startup cache via about:support, restart, installed:

```
XML Parsing Error: undefined entity
Location: chrome://dta-platform/content/manager.xhtml
Line Number 396, Column 9:
        <menu id="file-menu" label="&fileMenu.label;" accesskey="&fileMenu.accesskey;">
--------^
```

At least a change to before :)

WFx/ FFx version age: OK, understood.

BTW, renaming to .xpi is not necessary anymore, neither in WFx nor FFx: at some point in time installing as a .zip was enabled as long as the criteria inside the package are met.

macOS: if hackintosh isn't an option for you, do you know you can run macOS in either VirtualBox (free) or VMWare? It's rather simple.

**Comment by xiaoxiaoflood** [comment]
Thanks. Please test this new attempt.

[dta.zip](https://github.com/xiaoxiaoflood/firefox-scripts/files/7588435/dta.zip)

> BTW, renaming to .xpi is not necessary anymore, neither in WFx nor FFx: at some point in time installing as a .zip was enabled as long as the criteria inside the package are met.

I guess it depends on how you try to install it. If you drag-and-drop the .zip to about:addons or select it in "Install add-on from file", it works. But if you drop the .zip on a page like `example.com`, Fx prompts for download, while if you drop a .xpi file it still works.

**Comment by LeeBinder** [comment]
Amazing! Look:
![Bildschirmfoto 2021-11-23 um 15 08 52](https://user-images.githubusercontent.com/39203497/143039241-af5cc3c6-ab71-4d9a-b34d-f5a9828af36d.jpg)

You really know what you're doing, respect!

What's odd (already was like that with your current release build): when I click onto "Preferences", all looks OK:
![Bildschirmfoto 2021-11-23 um 15 07 50](https://user-images.githubusercontent.com/39203497/143039547-2913bec8-a0f4-4b08-b323-cf3f39b9ec56.jpg)

but as soon as I click onto any of the buttons in the window's tab (Interface, Network etc.):
![Bildschirmfoto 2021-11-23 um 15 07 26](https://user-images.githubusercontent.com/39203497/143039942-333b8d28-46a7-477c-98e6-c0343ca34f73.jpg)

even the General tab is empty when I click back onto it, so there must be a different execution or interpretation of the code when the prefs window is first displayed, and when a prefs page is activated via click onto a button in the prefs window.

**Comment by LeeBinder** [comment]
* sure enough first thing I did was to click onto "Restore Default Settings", but that did not make a difference, even after restart. And this behavior is the same in WFx and FFx.

**Comment by xiaoxiaoflood** [comment]
This issue doesn't exist here on W10. As soon as I can I'll try to debug it.

**Comment by LeeBinder** [comment]
The good news now already is that your DTA edition is functional - just did a test download. Also contextual menu and menu items work,like opening the download folder etc. 🥇

**Comment by LeeBinder** [comment]
.. and neither resizing nor maximizing the prefs window makes the content appear, so it doesn't seem to be a drawing issue (to help you narrow down debugging)

**Comment by xiaoxiaoflood** [comment]
As I said, there are layout issues for non-W10 OS, but the following version should be enough for basic usage of prefs window. Please, confirm that it's working and I'll push this update.

[dta-104.zip](https://github.com/xiaoxiaoflood/firefox-scripts/files/7597142/dta-104.zip)

**Comment by LeeBinder** [comment]
Yee-ha, you ROCK 👍 :
![Bildschirmfoto 2021-11-24 um 17 54 29](https://user-images.githubusercontent.com/39203497/143284888-ddb1445b-9767-4d69-aa76-76a1b675838c.jpg)

Even the tabs below the buttons work. Clicked many times forth and back - ALL GOOD in both latest WFx G4.0.3 and FFx 94.0.2. KUDOS!

So regarding update push:
![green thumb up emoticon](https://user-images.githubusercontent.com/39203497/143289311-9cc6256a-0860-4136-940b-1fb865698f5a.png)
