### ISSUE TITLE
fission related issue

### ISSUE THREAD

**Issue by clem2** [xiaoxiaoflood/firefox-scripts#106]
With fission enabled, loadframescript isn't working with cross-site iframes. Firefox 94.0.2. Fixable?

**Comment by xiaoxiaoflood** [comment]
Fission isn't enabled by default not even in Nightly ([bug](https://bugzilla.mozilla.org/show_bug.cgi?id=1732358)), so it may not be ready yet. When it's enabled in DevEd, if there's any issue I'll try to fix, but I guess there's no cross-site iframes in extensions and scripts from this repo.

As stated in issue template, please notice that this is not a place for general support about Firefox internals. I suggest you to use [Mozillazine Forum](http://forums.mozillazine.org/viewforum.php?f=19).
