### ISSUE TITLE
styloaix on FF96

### ISSUE THREAD

**Issue by sdavidg** [xiaoxiaoflood/firefox-scripts#108]
On https://github.com/xiaoxiaoflood/firefox-scripts/blob/d4b305adbf1681c0c254e144d420dd5ff75808c1/chrome/utils/styloaix/edit.js#L2 you need to change
`const {require} = ChromeUtils.import('resource://devtools/shared/Loader.jsm');` by `const {require} = ChromeUtils.import('resource://devtools/shared/loader/Loader.jsm');` for FF96

**Comment by xiaoxiaoflood** [comment]
Just upgraded to Fx 96. This is fixed now, thanks.
