### ISSUE TITLE
With newest DTA on FF95 the input field has invisible text.

### ISSUE THREAD

**Issue by mzso** [xiaoxiaoflood/firefox-scripts#109]
Hi!
So I noticed this since upgrading to latest devedition, all the way from 88 so the issue might be happening for a while. 
All the input fields on the DTA add downloads window are invisible. Since the window is mostly dark now which it was never before I think there were some css changes in FF that now affect the window. So the dark theme made the window dark and the text white, but the input field remained white, so white-on-white. I have to highlight text to see it.

Also, just now I noticed that the DTA button is missing from its usual place. And I don't see it in the repository either. Not sure if its a permanent issue.

(Once I noticed that downloads were added twice, but I couldn't replicate right now, so I'll keep an eye out for it)

**Comment by xiaoxiaoflood** [comment]
I just pushed an update to DTA! improving compatibility with dark theme.

**Comment by BozzaDaniel** [comment]
The latest API file appears to be corrupt. Firefox will not install it and it's not a valid zip-archive. Can you re-upload the latest version again?

**Comment by mzso** [comment]
[**@BozzaDaniel**](https://github.com/BozzaDaniel) commented on [2022. jan. 3. 12:31 CET](https://github.com/xiaoxiaoflood/firefox-scripts/issues/109#issuecomment-1004031975 "2022-01-03T11:31:32Z - Replied by Github Reply Comments"):
> The latest API file appears to be corrupt. Firefox will not install it and it's not a valid zip-archive. Can you re-upload the latest version again?

I don't know what you mean by "API file", but the latest version is fine. I've been using it for a while now.

**Comment by BozzaDaniel** [comment]
@mzso Sorry, I meant the XPI-file. Yesterday when i tried to install it didn't work, the downloaded XPI-file was only about 0.3 MB in size for some reason. Today when I tried to download it again the size was 1.5 MB and was able to install it. Something must have prevented the entire file from being downloaded.
