### ISSUE TITLE
Add hard reload option to rebuild_userChrome.uc.js

### ISSUE THREAD

**Issue by ArkadiuszMichalski** [xiaoxiaoflood/firefox-scripts#11]
Hi, now when we click Ctrl+Left Mouse on a given script we make reload this script (the same as turn off + turn on) but we operate with old cached script version. So every change done in our script need reload browser but it's pain always and always reload all browser (it's to heavy, especially when we have open more windows).
What if you add next option for reload, same as Ctrl+Left Mouse, but before that action you will remove all  profile\startupCache content. I noticed that when I do this manually then Ctrl+Left Mouse reload script with actual change.

**Comment by xiaoxiaoflood** [comment]
Every time I update one of my restartless scripts (e.g. rules in redirector.uc.js), the code updates instantly when I toggle the script (btw, double middle-click is easier for me than Ctrl+left-click). Make sure you are doing right to shutdown your script, the script should delete elements and vars in all open windows.

Try replacing
https://github.com/xiaoxiaoflood/firefox-scripts/blob/edaca64e696a216df3497e0f07786202bf7eaad6/chrome/utils/userChrome.jsm#L90

by

`    if (!script.regex.test(win.location.href) || (script.filename != this.ALWAYSEXECUTE && !script.isEnabled) || !script.file.exists()) {`

and let me know if this works for you.

`script.file.exists()` should recheck (reload) the file, so the updated code should be loaded here (with a different script.file.lastModifiedTime):
https://github.com/xiaoxiaoflood/firefox-scripts/blob/edaca64e696a216df3497e0f07786202bf7eaad6/chrome/utils/userChrome.jsm#L103

**Comment by ArkadiuszMichalski** [comment]
Hmm, it's strange, now I see all works fine without any change in rebuild_userChrome.uc.js , maybe some other app steal my CTRL. Double midle-click it is enough, I did not even notice such a good possibility. 

In future I will make connection with my text editor and the browser, so when change file in the editor my Firefox will automatically make above action (the glue will be Nodejs).

Btw,, on the occasion I have another question. I see on screen that you have some old addons like FindBar Tweak working in Nightly. When I use your all files and try instal this old addon I get message that files are corrupted. From console I get:
```
addons.xpi	WARN	Invalid XPI: Error: Non-restartless extensions no longer supported(chrome://userchromejs/content/BootstrapLoader.jsm:196:15) JS Stack trace: loadManifest@BootstrapLoader.jsm:196:15
```

I assume that every old addon must be manually adjusted to your loader? If yes can you share more addon for us? I see on that screen that you have footnote "-xiao" so probably you fix that addon. I'm just starting out with XUL and it will take me centuries before I move anything to the current version of Firefox.

**Comment by xiaoxiaoflood** [comment]
> you have some old addons like FindBar Tweak working in Nightly

I don't use Nightly, I prefer the stability of Developer Edition.

> I assume that every old addon must be manually adjusted to your loader?

Not to the loader, but to code changes in Fx since 57. Not a single addon will work on current Fx using just the bootstrap loader. For instance, my changelog for DownThemAll! to work in Fx 66:
https://i.imgur.com/hPviobv.png

I stopped using FindBar Tweak in Fx 58-59 because of some change in Fx code that would require major change in FBT. There was also changes in PDF.js... I think maybe I can write a UCJS to get back the only FBT feature I miss: marks in scrollbar. But I don't know if I'll ever work on it. I wrote a little prototype once, but there are many details to cover, frames, resizes... Never touched it again.

**Comment by ArkadiuszMichalski** [comment]
But I can't even install any addons, get popup that file is corruptet, this is because error is generatet at startap due changes in Firefox code or maybe the manifest has changed and need only small correct? I want only install addons, they do not have to work properly.

And I also miss marks in scrollbar the results of search, great future. I hope someone will implement it from FBT.

**Comment by xiaoxiaoflood** [comment]
You can install old addons, just follow the [instructions](https://github.com/xiaoxiaoflood/firefox-scripts/tree/master/extensions#instructions). FBT will install but will not work.

Note: I'm still on Fx 66, so they may not work on 67 or 68.

**Comment by ArkadiuszMichalski** [comment]
Ok, but you mean only your .xpi files or any others old addons? I just want install them, even if they don't work. But I get this:
![Schowek02](https://user-images.githubusercontent.com/2730894/55020825-f48e6580-4ff7-11e9-8b57-8ee224457c7d.gif)
I use both methods, all chrome files or bootstrapLoader.xpi. From 107 my old extension only one or two will installed but of course not work, but installing process will work, and I wondering what is going on.

**Comment by xiaoxiaoflood** [comment]
As, I said, "FBT will install but will not work".
Tried with [findbar-tweak-2.1.12.xpi](https://legacycollector.org/firefox-addons/308417/findbar-tweak-2.1.12.xpi) and bootstrapLoader.xpi.

I can't guarantee other legacy addon will install, I can't test now but I think addon from type overlay and SDK addon will not. FBT installs because it's a bootstrapped addon.

**Comment by ArkadiuszMichalski** [comment]
Ohh, now I understend, in fact, FTB is one of those that install. Now at least I know why. Thx for help, I'm going back to learning all of this XUL api.

**Comment by ArkadiuszMichalski** [comment]
@xiaoxiaoflood Hi, can you give me some advice on this problem? I will try create folder from some .jsm module (located inside utils folder), but this operation not work, script's stop works completely and don't get any error (even by using try-catch).
It's strange because below code work correctly form console, from any .uc.js scripts, or even from config.js, but not from any .jsm files.
```
var start =  Cc["@mozilla.org/file/directory_service;1"].getService(Ci.nsIProperties).get("ProfD", Ci.nsIFile);
let file = Cc["@mozilla.org/file/local;1"].createInstance(Components.interfaces.nsIFile);
file.initWithFile(start);
file.append("test");
file.create(1,0755); // this not work
```
I try google why from .jsm module we can't create files/folders but without any results.
