### ISSUE TITLE
Where are all the specifications (old) of the functions or whatever, of Mozilla?

### ISSUE THREAD

**Issue by Mitezuss** [xiaoxiaoflood/firefox-scripts#112]
"Now" is all WebAPI, but i wanna see the old site, are there a mirror ?

For example for nsIFrameScriptLoader

here: https://web.archive.org/web/20181208193129/https://developer.mozilla.org/en-US/docs/Mozilla/Tech/XPCOM/Reference/Interface/nsIFrameScriptLoader

But, i wanna know if there are sites of mozilla or unofficial (whatever), with all the old information

Thanks

**Comment by xiaoxiaoflood** [comment]
I don't know, and those old docs may be partially outdated. You should use searchfox.org.

Example: https://searchfox.org/mozilla-central/source/dom/chrome-webidl/MessageManager.webidl

But as you may have read in issue template, please note this is not a place for general support about Firefox internals. I suggest you to use [Mozillazine Forum](http://forums.mozillazine.org/viewforum.php?f=19).
