### ISSUE TITLE
Installing tab mix plus...blank addons screen when chrome folder added

### ISSUE THREAD

**Issue by harryray33** [xiaoxiaoflood/firefox-scripts#113]
I've followed the instructions and put in the chrome folder...Although Tab mix plus installs OK my addon manager is not showing the extensions, themes etc.

I tried removing any reference to addons in the BootstrapLoader.jsm file and restarted Firefox..the extensions now shoiw but I can't install Tabmix, I get a file is corrupt message.

Any ideas what to do please?

**Comment by harryray33** [comment]
I've upgraded to Firefox 88 and now the addons page is showing but Tab mix wont install...still getting the file is corrupt message

**Comment by 117649** [comment]
> I've upgraded to Firefox 88 and now the addons page is showing but Tab mix wont install...still getting the file is corrupt message

Of course you get that since you messed with BootstrapLoader.jsm.

And Firefox version to date should be 95 and plus.

Use an untainted file and clear startup cache.

**Comment by harryray33** [comment]
It happened before I changed the bootstraploader..I put in the files to my chrome folder and cleared the startup cache.
Do you mean it will only work with FF95 and above, will it not work with FF 88.0.1?

Thanks

**Comment by harryray33** [comment]
I've tried it with V. 0.5.8.1 and the dev build but it keeps saying corrupt.

When I originally tried to install it on my Firefox 69 it installed OK but the add-on page was blank, now it's the opposite problem that the add-on page is OK, but Tab mix wont install.

**Comment by 117649** [comment]
> It happened before I changed the bootstraploader..I put in the files to my chrome folder and cleared the startup cache. Do you mean it will only work with FF95 and above, will it not work with FF 88.0.1?
> 
> Thanks

You should also have some thing need to put in the Firefox install folder follow the instruction on this.





> I've tried it with V. 0.5.8.1 and the dev build but it keeps saying corrupt.
> 
> When I originally tried to install it on my Firefox 69 it installed OK but the add-on page was blank, now it's the opposite problem that the add-on page is OK, but Tab mix wont install.

Old addons only works on v57 or lower and new ones should only works on v78 or higher. The Firefox versions in between were immature messes no one can help.

**Comment by harryray33** [comment]
I'm now running 88 and it's not working..It was definitely working on 69 but I had the problem of the add-ons page disappearing

**Comment by 117649** [comment]
> I'm now running 88 and it's not working..It was definitely working on 69 but I had the problem of the add-ons page disappearing

Why 88 at all?

How you decided to use or even got that version?

Anyway use a proper Firefox version, install Bootstraploader properly and use newest TMP from github. 
If you got "corrupt" message it only means Bootstraploader is not working.
Oh, and Bootstraploader is not backward compatible, newest version should only works on newest version of Firefox.
If you want use a Firefox version too distant from current you have to dig out a Bootstraploader version that suit it from git history.

**Comment by harryray33** [comment]
I don't understand why it should have been installing OK with FF69 but not with 88. Does the current bootloader support 68 but not 88?

Where can I get different versions of bootloader?

**Comment by 117649** [comment]
> I don't understand why it should have been installing OK with FF69 but not with 88. Does the current bootloader support 68 but not 88?
> 
> Where can I get different versions of bootloader?

It may be able to install but it won't function.
Did you saw what you've installed back on 69 ever running and functioning properly?

If it so deeply fucked up it may allow you to install but the addon won't run anyway. 
When I upgrade my pre-57 profile to 95 I can see all my old addons in 95's addon manager but it means nothing at all they just can't run on 57 and above.

**Comment by xiaoxiaoflood** [comment]
You can get older versions from History. Like [here](https://github.com/xiaoxiaoflood/firefox-scripts/commits/master/chrome/utils/BootstrapLoader.jsm) and [here](https://github.com/xiaoxiaoflood/firefox-scripts/commits/master/extensions/bootstrapLoader/bootstrapLoader.xpi).

As stated, compatibility target is Firefox Developer Edition, currently in v96. Even ESR is in v91, so v88 for sure is not supported, let alone v69. It doesn't mean it won't work, just that nothing is or will be done to preserve compatibility with outdated versions.
