### ISSUE TITLE
bootstraploader not dispose addon sandbox or not reuse it properly?

### ISSUE THREAD

**Issue by 117649** [xiaoxiaoflood/firefox-scripts#115]
I just found that for my legacy addon after restart it some of it function calls that initiated by timer or observer callback are running in a sandbox context of the last startup which is different from current one. And this cause malfunctions for my addon.

**Comment by xiaoxiaoflood** [comment]
Yes... sure it's a bug, thanks.

But it wasn't me. BootstrapLoader is a product of Mozilla:
https://hg.mozilla.org/mozilla-central/rev/061b97e02ede#l3.320
