### ISSUE TITLE
Can you add EasyDragToGo+ to legacy extension list?

### ISSUE THREAD

**Issue by 117649** [xiaoxiaoflood/firefox-scripts#118]
![image](https://user-images.githubusercontent.com/8281345/152631151-b05fd445-3724-40d4-9121-c97f01402371.png)

@xiaoxiaoflood 
https://github.com/117649/EasyDragToGoPlus-Redux

**Comment by xiaoxiaoflood** [comment]
Of course! Done, thank you.

P.S.: you can use #81 if you want.

**Comment by 117649** [comment]
For some wired reason I've tried but failed to find #81 on the page when I was posting.
So I open a new issue, sorry for that.
May be because it was too early of the morning.
