### ISSUE TITLE
Black theme

### ISSUE THREAD

**Issue by Orriky** [xiaoxiaoflood/firefox-scripts#12]
Hi,

I use your scripts and I'm very satisfied.
I have a minor issue and I'm embarrassed to ask your help, but I hope you can help me.
Yesterday I was editing a script opened from your icon contextual menu in Firefox and I don't know how the notepad switched to a black theme. (Here a picture [https://imgur.com/EC9YOCZ](url))
I don't like it and I don't know how reverting this change

**Comment by xiaoxiaoflood** [comment]
Hi.

Closing this one as not related, my code doesn't turn anything to dark mode. Furthermore, Scratchpad doesn't exist anymore.
