### ISSUE TITLE
ColorfulTabs

### ISSUE THREAD

**Issue by DenBoxed** [xiaoxiaoflood/firefox-scripts#121]
Hi xiaoxiaoflood, 

I was wondering if it would be possible to add colorfultabs-31.2.3-fx.xpi to the list of extensions? 
https://accessfirefox.org/Colorful_Tabs.php

**Comment by 117649** [comment]
Looks like you are asking others to modernize this addon for you.

THE ANSWER SHOULD UNSURPRISINGLY BE NO.

**Comment by DenBoxed** [comment]
Any tips on how I can modernize it for others it 117649?

**Comment by DenBoxed** [comment]
> Looks like you are asking others to modernize this addon for you.
> 
> THE ANSWER SHOULD UNSURPRISINGLY BE NO.

Any tips on how I can modernize it for others 117649?

**Comment by 117649** [comment]
> > Looks like you are asking others to modernize this addon for you.
> > THE ANSWER SHOULD UNSURPRISINGLY BE NO.
> 
> Any tips on how I can modernize it for others OneAgreement?

Not very difficult in fact.
If the addon is not bootstrap type make it so. Give it a 'Bootstrap.js' file.
Then edit the script and CSS of it, replace all outdated objects, function calls.... and replace all XUL element with HTML element.
 
Check the [git history](https://github.com/117649/EasyDragToGoPlus-Redux/commits/main) of the EasyDragToGo+ see what change I made and how I made them, which should be a example simple and short.

**Comment by DenBoxed** [comment]
Thank you for the information, now that I have some idea what to do I'll give it a shot.

**Comment by DenBoxed** [comment]
@117649 I did a bit of editing, mind taking a look? https://gofile.io/d/3wf2c7 
I get the corrupt message but I might be overlooking something simple. 
Tweaked the install.rdf, and added bootstrap.js

**Comment by 117649** [comment]
You need an `<em:optionsType>1</em:optionsType>` node in 'install.rdf'.

**Comment by 117649** [comment]
![image](https://user-images.githubusercontent.com/8281345/156286567-ee00e368-ad6f-4859-ae48-00071913019e.png)
You can't mix node declare and attribute declare together.

**Comment by 117649** [comment]
A working install.rdf I've just made:
```xml
<?xml version="1.0"?>
<RDF:RDF xmlns:em="http://www.mozilla.org/2004/em-rdf#"
	xmlns:NC="http://home.netscape.com/NC-rdf#"
	xmlns:RDF="http://www.w3.org/1999/02/22-rdf-syntax-ns#">
	<RDF:Description RDF:about="rdf:#$lZf0J1"
		em:id="{ec8030f7-c20a-464f-9b0e-13a3a9e97384}"
		em:minVersion="52.0"
		em:maxVersion="56.0"
	/>
	<RDF:Description RDF:about="urn:mozilla:install-manifest"
		em:id="{0545b830-f0aa-4d7e-8820-50a4629a56fe}"
		em:unpack="true"
		em:type="2"
		em:name="ColorfulTabs"
		em:version="31.2.1"
		em:creator="Shivanand Sharma"
		em:description="Colorful Tabs colors every tab in a different color and makes them easy to distinguish while beautifying the overall appeal of the interface."
		em:homepageURL="http://www.addongenie.com/colorfultabs"
		em:optionsURL="chrome://clrtabs/content/clrtabsopt.xul"
		em:optionsType="1"
		em:bootstrap="true"
		>
		<em:targetApplication RDF:resource="rdf:#$lZf0J1" />
	</RDF:Description>
</RDF:RDF>
```

What I see here is your not yet have enough knowledge on how to this.
You should at least learn how to open Firefox browser toolbox, which would show you why install is failed. And its the most important tool you need for develop an addon.
![image](https://user-images.githubusercontent.com/8281345/156363463-227b1737-2612-4809-91d5-7ce26b34d69b.png)
Try learn more on yourself and try more. I won't always be here to answer your question.

**Comment by DenBoxed** [comment]
I've replaced all the xul elements with html. Only seem to be getting one issue trying to get options to load along with the icon.
![x1](https://user-images.githubusercontent.com/100437895/156856315-39f9154c-01cf-450d-a683-bfd0a58e8746.PNG)
![x2](https://user-images.githubusercontent.com/100437895/156856321-4aff6a12-2d2e-4e2a-add4-0a3233d313d3.PNG)
@117649 Apologies, still new to the whole world of extension modernization. I appreciate your time in explaining this stuff to me, thanks again. 

https://gofile.io/d/6yKOb6

**Comment by 117649** [comment]
You'd better to set up a git repo for your project and use a proper code editor like VS code. So you can track what you have changed and show others.

you've changed file name to 'clrtabsopt.xhtml' so change the paths reference it accordingly in 'chrome.manifest' and anywhere else.

I'm also left some words ahead of your next steps here.
 'clrtabsopt.xhtml' uses 'prefwindow' element which is no longer part of the Firefox but fortunately you can find script for that in TMP's source.
You'll need a way to load the contents of 'clrtabs.xml', you can also find 'overlay.jsm' in TMP's source for that.
Some early issues on repo of TMP should be very useful to you.

**Comment by DenBoxed** [comment]
I set up the repo, https://github.com/DenBoxed/Colorfultabs. Started using VS code, pretty neat with the side by side comparison option built in.  Checked TMP's source and found preferences which seems to match up with prefwindow. Also added in overlay.jsm. Still running into a bug but I think I patched it. The options page is loading but just wide. @117649

**Comment by DenBoxed** [comment]
Referenced @117649 https://github.com/DenBoxed/Colorfultabs/releases/tag/ctlrtabs

**Comment by DenBoxed** [comment]
@xiaoxiaoflood Mind taking a look at the addon and giving me some feedback?

**Comment by xiaoxiaoflood** [comment]
Never used this addon, all I can say is that I tried it and doesn't seem to work. Nothing has changed in tabs and [preferences dialog is broken](https://user-images.githubusercontent.com/25161346/163888817-92b804f6-5558-4982-b2f4-57d7e04dbc97.png).
