### ISSUE TITLE
Resurrect All in one sidebar and Autopager (the only one)

### ISSUE THREAD

**Issue by Tsharii** [xiaoxiaoflood/firefox-scripts#122]
Hello,

I found your work by trying to install TMP from onemen and I think it is a beautiful thing.
Get a status bar, some legacy extensions back from the very good past of Firefox. Enhancements to the present from the past.

It is sad that the title bar hiding option doesn't work anymore. We lose some precious space to put something more useful.

I think about the Firefox current version sidebar, and I see that is not really good.
For sure, web extensions exists to put more and more things to that cheap new sidebar, but it's not a state of the art, like all in one sidebar.

I want to add a side toolbar, as a beginning, to put buttons that opens history, bookmarks, a compact list of extension, themes and plugins, dictionaries and languages. This will be more friendly than all those tabs what loose the user in a jungle of tabs functionalities.

To do this, I will try to adapt the status bar script to bring a toolbar at the left (or right) of the browser. 

So I need a little help from anywhere to do this, a guide to make me take the right road to success that project.

I'm sure that AIOS can be handled by the Firefox-scripts like TMP, there are the two pillars that made Firefox a really good browser used as an alternative to all of the AIOS was for the sidebar what TMP was (and be again) to the tab bar and tabs.

Meanwhile, I will try to contact the AIOS author to get the newest extension code he wrote before retiring AIOS from us.

Autopager will be next.

Kind regards,
RC also known as Tsharii.

**Comment by 117649** [comment]
You can check the git history of existing modernized addons.
[Like this one](https://github.com/117649/EasyDragToGoPlus-Redux/commits/main)

**Comment by Tsharii** [comment]
Thank you, @117649.
That would help.
