### ISSUE TITLE
Current DownThemAll version doesn't want to install to FF 91.8.0 ESR

### ISSUE THREAD

**Issue by lokapal** [xiaoxiaoflood/firefox-scripts#128]
Could you fix, please, current DownThemAll.xpi (dta.xpi namely) to permit installation to Firefox 91.8.0 ESR? Or ask maintainer to do it? Right now I found in archives old version 3.1.2.96.2021.12.27-xiao and installed it, but it's seems to be the better choice to have access to the latest version. Thanks in advance!

**Comment by xiaoxiaoflood** [comment]
As stated [here](https://github.com/xiaoxiaoflood/firefox-scripts/tree/master/extensions#readme), compatibility is only checked with Developer Edition. I don't provide any backward compatibility to make maintenance easier, sorry.

There was a minor change in Fx 94 code that enforced an update to DTA!. You can manually open the *.xpi* file with any archiver (it's just a renamed ZIP) and adjust `minVersion` in *install.rdf*, the extension should work normally, you just won't be able to see minor warnings (notifications).

Or just use the [proper version](https://github.com/xiaoxiaoflood/firefox-scripts/blob/b45faa625c02a68f494c24ee791c7bafe7b4e862/extensions/DownThemAll/dta.xpi) compatible with Fx 91.
