### ISSUE TITLE
Help with user script

### ISSUE THREAD

**Issue by r-a-y** [xiaoxiaoflood/firefox-scripts#13]
Hi xiaoxiaoflood,

I'm trying to convert an older legacy extension to a userscript:
[https://addons.mozilla.org/en-US/firefox/addon/auto-focus-url-bar/](https://web.archive.org/web/20171102130512/https://addons.mozilla.org/en-US/firefox/addon/auto-focus-url-bar/)

Source:
https://pastebin.com/bNpXZDN1

It appears that this script only works with e10s disabled and I'm not sure how to convert it to get it working with e10s.  Some APIs probably need to replaced, but I'm not familiar enough with XUL to get it working:
https://developer.mozilla.org/en-US/docs/Archive/Add-ons/Add-on_SDK/Guides/XUL_Migration_Guide#Using_XPCOM

Any help would be appreciated.

**Comment by xiaoxiaoflood** [comment]
Hi,

In e10s world you need to use message managers to interact with tab content.

https://developer.mozilla.org/en-US/docs/Mozilla/Firefox/Multiprocess_Firefox/Message_Manager/Message_manager_overview

Sorry, but I have no time to fix other legacy addons.

I use 'a' as hotkey to focus urlbar (with [keyconfig](https://github.com/xiaoxiaoflood/firefox-scripts/tree/master/extensions/keyconfig)). No Ctrl, no Shift, no Alt, just 'a', and you will still be able to type 'a' normally in text fields, as the hotkey only acts when no text field is focused. Just saying, maybe it will suit you too.

**Comment by r-a-y** [comment]
Thanks for the workaround with keyconfig. Just tested it and that kind of works!
