### ISSUE TITLE
Mouse gestures: need to set ui.context_menus.after_mouseup = true

### ISSUE THREAD

**Issue by sj2tpgk** [xiaoxiaoflood/firefox-scripts#133]
I'm on linux, firefox 99.0.1, and using mouseGestures.uc.js.

**ui.context_menus.after_mouseup** must be set to **true** for gestures to work, otherwise context menu shows up on mousedown before gestures start getting recognized.

This is not needed on Windows though. https://bugzilla.mozilla.org/show_bug.cgi?id=1419426#c4

I think this should be noted in readme like:

> On non-Windows platform, you need to set ui.context_menus.after_mouseup = true in about:config.

**Comment by xiaoxiaoflood** [comment]
Done directly in the script.

66acdf69bd3a4a9e316fa4471339950aa329185a
