### ISSUE TITLE
The plugin icon is missing.

### ISSUE THREAD

**Issue by rediffusion** [xiaoxiaoflood/firefox-scripts#136]
Hello! 🙂

I pressed the icon on Tools Menu > User Scripts > "Switch to item in Tools Menu". How can I get it back?

---
![User Scripts](https://user-images.githubusercontent.com/30071027/168496068-efde05a6-1dbf-4b4e-a8f1-e718fc03c810.png)

**Comment by xiaoxiaoflood** [comment]
Enable Menu Bar (one way to do it temporarily is by pressing Alt), `Tools` → `userChromeJS Manager` → `Switch to button in Navigation Bar`.

Or simply open `about:config` and toggle `userChromeJS.showtoolbutton`.
