### ISSUE TITLE
chrome/redirector.uc.js bug

### ISSUE THREAD

**Issue by 0rt** [xiaoxiaoflood/firefox-scripts#145]
```
 [
    //Remove unnecesary ? and &
    /(?:(\?)(?:&+(?!$|&)))|(?:&(?=&))|(?:(?:\??&+|\?)$)/g,
    '$1'
  ]
```

This rule will redirect bing.com search result to wrong page. I got search result like:
https://www.bing.com/ck/a?!&&p=23ccaab8597a7dd028d1df710d9e69d54de6f14093cbf4163050769ddef34978JmltdHM9MTY1NDg1NjI1NiZpZ3VpZD0yZmNmMTMxYy0zMGQwLTRiNTYtYjZkNy1mMmNiYmIzNzdiYTQmaW5zaWQ9NTE1OQ&ptn=3&fclid=8c2d56b2-e8a6-11ec-a223-1ac7fdae5f30&u=a1aHR0cHM6Ly93d3cuc3FsaXRlLm9yZy9zcmMvaGVscD9jbWQ9bWVyZ2U&ntb=1

I will redirct to wrong site if the uc.js is enabled

**Comment by 0rt** [comment]
Could you please consider adding some console.log message for the redirector? It's not easy for user to tweak those rules even if they got the know the ABC of javascript, at least which rule is applied would help a lot.

**Comment by xiaoxiaoflood** [comment]
You may want to append `console.log(redirectUrl);` right after this line:
https://github.com/xiaoxiaoflood/firefox-scripts/blob/77f56676dc6686af15827f9d51c1e4d3e0989c2a/chrome/redirector.uc.js#L121

That's all I can do.
