### ISSUE TITLE
cannot ignore signatures

### ISSUE THREAD

**Issue by halt76** [xiaoxiaoflood/firefox-scripts#146]
I have only tried with Tab MIx Plus, but it seems that since Firefox 102.0b7, it cannot ignore signatures.
Can you do something about this?

**Comment by xiaoxiaoflood** [comment]
The only treatment about signature is here:

https://github.com/xiaoxiaoflood/firefox-scripts/blob/ad2061bdaa9a5f77967029741a16614699a99f3a/installation-folder/config.js#L2

I'm using Fx 102.0b7 with everything in this repo without any issue. Just be sure to have the latest version of each involved file.

**Comment by halt76** [comment]
No, you can't.

fx-folder.zip, utils.zip are up to date.
In about:config I see that xpinstall.signatures.required is locked.
I cannot install TMP with the new profile. (Cannot validate signatures).
TMP is disabled in the old profile. (Cannot validate signatures)
I cannot get it to work no matter how many times I reboot.
It is working perfectly up to 102.0b6.

What else can I do?

**Comment by xiaoxiaoflood** [comment]
I can't what?

Are you using Fx DevEdition like me or are you using Fx Beta?

I just realized the patch forcing `AppConstants.MOZ_REQUIRE_SIGNING` = `false` no longer works, it's needed for release and Beta users cause it's `true` for them.

I published an update with a different approach I tested here and worked with a fresh new Beta v102.0b7 and a fresh new profile.

Please update your [config.js](https://github.com/xiaoxiaoflood/firefox-scripts/raw/63a9091c2b371a193d494302abd4d583693cf78c/installation-folder/config.js) (or [fx-folder.zip](https://github.com/xiaoxiaoflood/firefox-scripts/raw/63a9091c2b371a193d494302abd4d583693cf78c/fx-folder.zip)) then restart Fx clearing startup cache (step 6 in readme).

**Comment by halt76** [comment]
I'm using fx beta.
config.js was updated and confirmed that the signature was no longer verified by 102 beta 8.
thanks.
