### ISSUE TITLE
Installation of cookie-related extensions fails with latest fx-folder.zip

### ISSUE THREAD

**Issue by jiangzhenjerry** [xiaoxiaoflood/firefox-scripts#148]
With the latest `fx-folder.zip` (updated 2022-06-16T05:36:04Z, commit [63a9091](https://github.com/xiaoxiaoflood/firefox-scripts/commit/63a9091c2b371a193d494302abd4d583693cf78c)), installation of cookie-related extensions will fail.

For example:
https://addons.mozilla.org/en-US/firefox/addon/cookiebro/
https://addons.mozilla.org/en-US/firefox/addon/export-cookies-txt/
Note these are not legacy add-ons.

- The error message says `Installation aborted because the add-on appears to be corrupt.`
- Saving the `.xpi` files locally and dragging them to the Firefox windows also fail.
- After deleting `config.js`, there is no problem. But then of course legacy add-ons won't work.

<img width="581" alt="sshot-1" src="https://user-images.githubusercontent.com/9311082/174463052-54dbe356-f30e-4f60-8a34-b4e55d1381e0.png">

**Comment by xiaoxiaoflood** [comment]
Thanks for reporting. This should be fixed now.
