### ISSUE TITLE
DTA doesn't have most of the options

### ISSUE THREAD

**Issue by nearcatch** [xiaoxiaoflood/firefox-scripts#155]
Firefox Dev 103.0b1 (64-bit)

DownThemAll 3.1.2.99.2022.03.14-xiao is missing most of DTA's options dialog. There should be tabs to create/modify custom filters and create/modify domain-specific limits, but that's all gone.

Options don't appear to be saved in this dialog either. I tried checking the box for listing flash videos but it wasn't selected when I opened the options dialog again.

xiao options menu, missing Filters tab and Network tab:
![image](https://user-images.githubusercontent.com/692914/176785918-d5ad8ca8-db49-4b47-b4e1-17b48d94c9d9.png)

**Comment by xiaoxiaoflood** [comment]
Fixed, just update DTA!.
