### ISSUE TITLE
Tabs Context Menu missing item

### ISSUE THREAD

**Issue by eilegz** [xiaoxiaoflood/firefox-scripts#156]
Only using the status bar script but i have a weird issue with my context menu on the tabs specifically

![tab context menu](https://user-images.githubusercontent.com/108883926/177800330-4e0c2854-f072-4f52-8783-d332e91aa10e.png)

**Comment by xiaoxiaoflood** [comment]
Can't reproduce and it makes no sense for me this is statusbar's fault.

If you can find a way to tell steps to reproduce in a new profile, please let me know and if the issue is in some code of mine I'll try to fix it.
