### ISSUE TITLE
StyloaiX breaks firefox theme when 2 AGENT_SHEET files are enabled

### ISSUE THREAD

**Issue by Sneakpeakcss** [xiaoxiaoflood/firefox-scripts#157]
<sub>Firefox 102.0ESR, Win10Pro, Clean profile with newest StyloaiX+loader</sub>

Looks like something broke between ESR91-ESR102:

1. Turn firefox dark theme on.
2. Create 2 AGENT_SHEET files in StyloaiX (blank files will also 'work').
3. Restart firefox.

![1broken](https://user-images.githubusercontent.com/77424331/178132630-e774d035-9b67-4209-a671-c7682933db23.png)

With only 1 AG file enabled it works correctly:
![2working](https://user-images.githubusercontent.com/77424331/178132658-7e67d33a-8a41-443c-981e-d052b158cdb1.png)

**Comment by xiaoxiaoflood** [comment]
Thanks for reporting. This is a Firefox bug, but I pushed an update that fixed it for me, could you please test it?

**Comment by Sneakpeakcss** [comment]
> Thanks for reporting. This is a Firefox bug, but I pushed an update that fixed it for me, could you please test it?

<sub>102.2.0esr/WIN10</sub>
Works on my side without a problem.

Thanks for the update.
