### ISSUE TITLE
Not working on FF69

### ISSUE THREAD

**Issue by rayman89** [xiaoxiaoflood/firefox-scripts#16]
Since the update to firefox 69 this method has stopped working. Is it possible to modify it somehow to make it work again?

**Comment by flandy** [comment]
According to https://bugzilla.mozilla.org/show_bug.cgi?id=1534407, 
https://github.com/xiaoxiaoflood/firefox-scripts/blob/3079cc5089368bd10083896c37fa80153265fab5/chrome/utils/userChrome.jsm#L10 should be changed to
`BROWSERCHROME: 'chrome://browser/content/browser.xhtml',`
on version 69+.

Other uc.js and css files should be modified accordingly. You can refer to https://www.firefox.net.cn/read-121106-1 for more details (in Chinese).

**Comment by rayman89** [comment]
Thank you.

**Comment by peterwx** [comment]
It isn't working for me (FF dev 69). 
To test the setup i enabled minMaxCloseButton.uc.js and userScript manager(rebuild_userChrome.uc.js) and for caution disabled css customizations(chrome and content). The script manager won't work: no icon, no popup either from nav_bar or overflow menu. If one moves it to customization ui left icon grid, it lists as userChromeJS.
Removing it from overflow menu and toolbar from the context menu has no effect on the layout mess of the overflow menu(reduced height, vertical scrollbar, some or all addon entries invisible) but renaming the file extension does resolve the problem with the layout.
However with a single .uc.js enabled (ex: titlebar_moveable or minMaxClose-only the former appeared) and no manager, the nav_bar layout is a mess: half of the nav_bar space before the overflow menu is created(wasted).
I have followed the proper steps with the latest files and @flandy tip above, except some commenting out which didn't affect the outcome on previous FF version 67 or 68. I left commented the boot.jsm addons part(i do not use legacy addons) and locked prefs.
To note that i didn't find any 'general.config.sandbox_enabled' in about:config despite being set in config-prefs.js.

**Comment by peterwx** [comment]
It isn't working for me (FF dev 69). 
To test the setup i enabled minMaxCloseButton.uc.js and userScript manager(rebuild_userChrome.uc.js) and for caution disabled css customizations(chrome and content). The script manager won't work: no icon, no popup either from nav_bar or overflow menu. If one moves it to customization ui left icon grid, it lists as userChromeJS.
It messes the layout of either the nav_bar or overflow menu by making invisible all the items to its right or below, but renaming the file extension does resolve the problem with the layout. The minMaxClose script also has similar problems.
However with a single .uc.js enabled (ex: titlebar_moveable) and no manager the layouts are fine.
I have followed the proper steps with the latest files and @flandy tip above, except some commenting out which didn't affect the outcome on previous FF version 67 or 68. I left commented the boot.jsm addons part(i do not use legacy addons) and locked prefs.
To note that i didn't find any 'general.config.sandbox_enabled' in about:config despite being set in config-prefs.js.

**Comment by peterwx** [comment]
Indeed it works. Following @flandy's tips (the browserchrome switch and the no so clear chinese instructions).
I have taken the chinese part meaning to replace document.createElement with document.createElementNS("http://www.mozilla.org/keymaster/gatekeeper/there.is.only.xul", elTagName) and got scripts and script manager working.

**Comment by xiaoxiaoflood** [comment]
Fixed.
