### ISSUE TITLE
Latest Nightly build breaks DownThemAll

### ISSUE THREAD

**Issue by jiangzhenjerry** [xiaoxiaoflood/firefox-scripts#160]
The latest Nightly build (7/11 USA evening) seems to break DTA. DTA doesn't function at all, even though it is enabled in about:addons.
https://ftp.mozilla.org/pub/firefox/nightly/2022/07/2022-07-11-21-56-41-mozilla-central/firefox-104.0a1.en-US.win64.installer.exe

Note that the previous Nightly build (7/11 USA morning) works fine:
https://ftp.mozilla.org/pub/firefox/nightly/2022/07/2022-07-11-09-48-52-mozilla-central/firefox-104.0a1.en-US.win64.installer.exe

I only tested DTA - other extensions may have been affected, too.

**Comment by nearcatch** [comment]
Can confirm that 3.1.2.103.2022.07.03-xiao is broken on Firefox 104.0b3 (64-bit) on Windows 10.

**Comment by xiaoxiaoflood** [comment]
Thanks. Extension updated, it's working for me in Fx 104.

Hopefully it also works on Nightly, but I can't assure because I only test things on Developer Edition.

**Comment by jiangzhenjerry** [comment]
Thank you for the fix. I tested it on the today's Nightly 105, and it works so far. Appreciated.
