### ISSUE TITLE
is possible to have legacy Flashgot

### ISSUE THREAD

**Issue by Janaue** [xiaoxiaoflood/firefox-scripts#161]
I used flashgot a lot with palemoon and old firefox. I would like to have it with modern firefox
https://flashgot.net/getit#devel
is it possible to make it compatible like it was done for DTA ?

**Comment by siamak2** [comment]
I'm using `DownloadGrab` as alternative for flashgot.
You can download it from this repository:
https://github.com/pouriap/Firefox-DownloadGrab/

**Comment by Janaue** [comment]
ok. I like flashgot because it detects more videos where in some cases the various addons for the new firefox fail.
A nice addition is the ''gallery'' which permits to cram lots of links in only one page, then DTA takes all those. 
If you have time in the next few months, please consider porting flashgot to the new firefox.
