### ISSUE TITLE
private tab script not really working anymore

### ISSUE THREAD

**Issue by Ulf3000** [xiaoxiaoflood/firefox-scripts#165]
all visited sites in a "private tab" will be added to the history .. ff102

**Comment by xiaoxiaoflood** [comment]
Working fine for me in Fx 104. Make sure to have the latest version of everything (privateTab.uc.js, utils folder...), then clear startup cache before restarting Fx.

**Comment by Ulf3000** [comment]
sorry im dumb  , it seems that i disabled the script , but the private container still persisted and me not getting it , after re-enabling the script everythings working fine ... #whenyouhavetoomanyuserschromescriptsinstalled

can be closed
