### ISSUE TITLE
Can't access legacy addon options via Extension Options Menu or Add-ons Manager

### ISSUE THREAD

**Issue by TFWol** [xiaoxiaoflood/firefox-scripts#167]
One of the recent updates seems to have made managing legacy addons more difficult.

I've been able to get to the settings of addons who expose the option through their own menus like Download Manager, but haven't been able to access them through normal means (see title)

**Workaround URLs for addons options page:**
- Link Status Redux
    - chrome://linkstatusredux/content/options.xhtml

**Comment by xiaoxiaoflood** [comment]
Probably caused by the removal of `browser.preferences.instantApply` in Fx 103. Get latest extensionOptionsMenu.uc.js and BootstrapLoader.jsm (or bootstrapLoader.xpi).

It's working for me in Fx 104.

**Comment by TFWol** [comment]
Ah, I had applied the bootstrap, but failed to apply the newer extensionOptionsMenu.
Thanks, working.
