### ISSUE TITLE
Link Status Redux %t (second visit time) not populating

### ISSUE THREAD

**Issue by TFWol** [xiaoxiaoflood/firefox-scripts#169]
While trying to have both the first time (%t) I've visited a link next to the latest time (%T), I've noticed %t won't fill in a value.

**Comment by xiaoxiaoflood** [comment]
Works for me. Maybe you didn't understand `Prefer visit time older than` option?
If you visit the same link two minutes ago and now, but your `Prefer visit time older than` is higher than `120` (2 minutes), then LSR will display only one visit.

My `Prefer visit time older than` is `600`, so I only get two times in LSR if I visited the link most recently than 10 min ago **and** I have a visit older than 10 min ago. It's not enough to visit it twice in last few minutes.

**Comment by TFWol** [comment]
Yep, that was it. Thanks.
I guess the wording was a bit confusing for me. I've gone ahead and set mine to match yours for the desired result.
