### ISSUE TITLE
eval(script.startup); made Nightly crash

### ISSUE THREAD

**Issue by ArkadiuszMichalski** [xiaoxiaoflood/firefox-scripts#17]
@xiaoxiaoflood 
Hi, looks like that in last Nightly invoking `eval(script.startup);` in `loadScript()` made crash browser. Script without `@startup` directive works correct. Can you confirm? Yesterday all works fine, today I got Nightly update and all stop working. They change something around `eval()` funciton?

**Comment by xiaoxiaoflood** [comment]
Probably fixed in Fx 70 (https://bugzilla.mozilla.org/show_bug.cgi?id=1567623).
