### ISSUE TITLE
DownThemAll Columns Squeezed in Nightly (8/23/2022)

### ISSUE THREAD

**Issue by jiangzhenjerry** [xiaoxiaoflood/firefox-scripts#170]
The following bug can be observed in Firefox Nightly starting 8/13/2022:
https://ftp.mozilla.org/pub/firefox/nightly/2022/08/2022-08-13-09-22-39-mozilla-central/

In the "Make Your Selection" window, the total width of columns is confined to a small degree, and hence every column is squeezed.
<img width="509" alt="2022-08-13_131945" src="https://user-images.githubusercontent.com/9311082/184509740-5ee53362-98ff-4731-983e-ea6b2e15731b.png">

**Comment by marty60** [comment]
Same with Password Manager.

**Comment by hgdagon** [comment]
I have the same issue. Additionally the status bar is not readable in dark mode. The entire window is in dark mode except for the status bar, which results in a white font on a light background.

**Comment by xiaoxiaoflood** [comment]
I just released an update, this should be fixed now, at least on Fx 105.
