### ISSUE TITLE
BackTrack fails for tabs created from unloaded tab

### ISSUE THREAD

**Issue by xiaoxiaoflood** [xiaoxiaoflood/firefox-scripts#173]
@AlexVallat

Steps to reproduce:
1. Set Firefox to restore previous tabs.
2. Having at least two unpinned tabs, like one in Google and other in GitHub, restart Firefox.
3. At least one tab from last session will start unloaded. Activate it, wait it to load then open a link in new tab. For instance, the unloaded tab was Google main page, so you middleclick to open Google Images. The newly created tab doesn't inherit history from parent, "go back" button is unavailable, that's a bug.

From my experience, this only happens when parent tab was unloaded at some point in current session. If I open Google in a new tab then middleclick "Images", that way BackTrack works and Google Images loads with history from parent, I'm able to go back to Google main page.

**Comment by AlexVallat** [comment]
Thanks for reporting this, I can reproduce the issue. I will investigate and see if any resolution is possible.

**Comment by xiaoxiaoflood** [comment]
Thanks!
