### ISSUE TITLE
SaveFileTo and Buggy Page Info

### ISSUE THREAD

**Issue by SenpaiSharp** [xiaoxiaoflood/firefox-scripts#18]
In SaveFileTo, when you go to the Page Info and the Media tab and pick an image file, the Save As button doubles into a "Save As Save As" button. The positioning is a bit weird and the drop menu button also just brings up the Save Dialog window instead of the SaveFileTo list.

**Comment by xiaoxiaoflood** [comment]
Yes, this is a known issue, caused by [bug 1450652](https://bugzilla.mozilla.org/show_bug.cgi?id=1450652) (Fx 67). For now I had no motivation to work on it, since I never use Page Info.

**Comment by SenpaiSharp** [comment]
I rarely use it either but it is useful on the occasion that a site makes their images complicated to click on.

**Comment by xiaoxiaoflood** [comment]
I use DownThemAll!, its selector should be useful on these occasions.

But I should fix this, it's just not a priority. First I need to fix DownThemAll! for Fx 69, for instance.

**Comment by xiaoxiaoflood** [comment]
Fixed.

![](https://i.imgur.com/MJ9ZJmp.png)
