### ISSUE TITLE
DownThemAll cannot intercept download link since FF 100

### ISSUE THREAD

**Issue by lokapal** [xiaoxiaoflood/firefox-scripts#180]
Hello!

   DownThemAll cannot intercept download links since approximately FF 100. In my FF 91.13.0 ESR all is working without any problems, in FF 102.3.0 ESR under Windows/Linux all DTAs cannot intercept links to files so at click to the link no question about how do I want to download the file arises and so all downloads are go to FF by default.

  And one more feature request - can you advice how to make compatible with your scripts the DTA's companion - MinTrayr (at least, for Windows)? I guess it's only the question of headers. The most fresh version is here: https://github.com/ysard/mintrayr Can you add it (modified) to your extension repository?

**Comment by xiaoxiaoflood** [comment]
Open Firefox Settings and scroll down to `Applications`. In the table, file types that you want download dialog to be displayed should be set as `Always ask`. Then select `Ask whether to open or save files` right below the table for other files.

![image](https://user-images.githubusercontent.com/25161346/193699924-bd477aa8-1c34-4525-ae13-2f885499cb45.png)

Regarding the other matter, sorry but it's not trivial to revive legacy addons so I can't help you with that.
