### ISSUE TITLE
Broken S3Download toolbar button

### ISSUE THREAD

**Issue by nollinvoyd** [xiaoxiaoflood/firefox-scripts#183]
I've been using the original S3Download for quite some time.  I upgraded to your version.  

There is an issue with the toolbar button.  It does not appear on the toolbar after installation.  When I opened "Customize Toolbar" it appeared on the toolbar, in the same position as the old version,, but when I closed "Customize Toolbar", it vanished once again.  I tried to move it from my navigation bar to my menu bar to see if that would help, but again, it vanished when closing "Customize Toolbar".

Now, even if I go to "Customize Toolbar", it is not present.

**Comment by xiaoxiaoflood** [comment]
S3D toolbar button isn't displayed by default when downloads list is empty.

Open S3D settings, `General` tab, `Statusbar Mode` sub-tab, select `Auto Mode` and uncheck `hide Mini Mode icon when download list is empty`.

It's working for me on Fx v106.

**Comment by nollinvoyd** [comment]
Great :)

I know you're very busy, but there's one other issue I just ran across.  

I have my desktop toolbar on top.  I didn't realize until you mentioned it that there were any setting tabs because they hide under the toolbar

![s3d0](https://user-images.githubusercontent.com/20844322/193706392-ad8c50be-0baf-438b-a98c-0e4417556180.png)

I figured I'd mover the toolbar to the side to see if the tabs would be revealed, but still hidden

![s3d](https://user-images.githubusercontent.com/20844322/193706655-86d79951-6af9-4ee6-bd2d-c6c98f6d376e.png)

I moved the toolbar back, and the tabs showed up, But I did notice some settings at the bottom of the interface were not accessible

![s3d2](https://user-images.githubusercontent.com/20844322/193706760-fe33a04d-bfd8-4109-92b5-b5f6ffa03e73.png)

![s3d4](https://user-images.githubusercontent.com/20844322/193707502-284722f2-c67f-4bd1-a55e-ee511de17c5c.png)

**Comment by xiaoxiaoflood** [comment]
It should be working know with latest version, feel free to comment if something is wrong.
