### ISSUE TITLE
No extensionsUpdateChecker.uc.js toolbar button

### ISSUE THREAD

**Issue by nollinvoyd** [xiaoxiaoflood/firefox-scripts#184]
Perhaps I'm mistaken.  Is there supposed to be a toolbar button?

The description says it's supposed to act after the daily check.  Is that when the browser is launched? If so, I get no notifications that updates are available.

Also, what is the significance of the items in blue?  Edit: ok  I found the answer :)

**Comment by xiaoxiaoflood** [comment]
There's no toolbar button.

The daily check is done automatically by Firefox under the hood. If there's any available update, a new tab will open in `Add-ons Manager` pointing to `Available Updates`.
