### ISSUE TITLE
10/8/2022 Firefox Nightly breaks DownThemAll

### ISSUE THREAD

**Issue by jiangzhenjerry** [xiaoxiaoflood/firefox-scripts#185]
Firefox Nightly this morning breaks DownThemAll:
https://ftp.mozilla.org/pub/firefox/nightly/2022/10/2022-10-08-09-36-24-mozilla-central/

<img width="644" alt="0" src="https://user-images.githubusercontent.com/9311082/194725636-dfebb6fb-8eb4-4860-8ac4-ef15c989f0b9.png">

**Comment by marty60** [comment]
Broke here too. They also messed up Password Manager again just days after it was fixed.

**Comment by xiaoxiaoflood** [comment]
Fixed now.
