### ISSUE TITLE
rebuild_userChrome is but button is hidden

### ISSUE THREAD

**Issue by oghmios** [xiaoxiaoflood/firefox-scripts#19]
Hi,

I clicked on an option that not remember the name(inside that extension) and now I dont have access to this button(is hidden but working, because firefox aks me for a password). How can I see aggain the button?

**Comment by SenpaiSharp** [comment]
Are you referring to "Switch to item in Tools Menu"?

Check **Tools** in your **Menu Bar** and see if **userChromeJS Manager** is in there. Inside the nest of the same name you can choose **Switch to button in Navigation Bar**.

**Comment by oghmios** [comment]
Is not in there, but i have it in chrome folder. How can I re activate it?

**Comment by xiaoxiaoflood** [comment]
`userChromeJS.showtoolbutton = false` or right-click anywhere in navbar -> Customize and drag the icon back to the toolbar.
