### ISSUE TITLE
[Styloaix] should create CSS Dir with 0775

### ISSUE THREAD

**Issue by fuyu0425** [xiaoxiaoflood/firefox-scripts#193]
https://github.com/xiaoxiaoflood/firefox-scripts/blob/c9ad50550b18bcce78046362b137613335da997b/chrome/styloaix.uc.js#L354

Lack of execution permission for CSS Dir (rw- instead of rwx) will prevent file saving on MacOS.
I manually `chmod +x UserStyles` and the save function finally works. 
Not sure whether it's macOS-specific issues.

OS: OSX 10.15.7
Firefox version: Firefox Developer Editor (107.0b2)

**Comment by xiaoxiaoflood** [comment]
Latest StyloaiX is now using 0755, the same Firefox uses for [FileUtils.PERMS_DIRECTORY](https://github.com/mozilla/gecko-dev/blob/e51b2630b44a8836a7ff35a876a2d8b555041d4a/toolkit/modules/FileUtils.sys.mjs#L15). Please let me know if it still doesn't work for you.
