### ISSUE TITLE
aboutconfig.xhtml page not opening

### ISSUE THREAD

**Issue by davix004** [xiaoxiaoflood/firefox-scripts#194]
Hello,
The new about:config page (chrome://userchromejs/content/aboutconfig/aboutconfig.xhtml) form utils folder doesn't open anymore in the new beta 107 firefox win64 version. I tested with new profile and reinstalling firefox from scratch, with no avail. When I try to open the new about.config page, it opens a page with "This might void your warranty" warning" but the about:config doesn't open at all when I click in the "I accept the risk" button. 
Two warning messages show up in devtool DOM tab : "onmozfullscreenerror is deprecated." and "onmozfullscreenchange is deprecated."
And one of three different warning messages appear when I reload the tab multilpe times: one time it's "Style sheet could not be loaded. chrome://global/skin/in-content/info-pages.css", another time "Style sheet could not be loaded. resource://gre-resources/mathml.css", or "Style sheet could not be loaded. chrome://global/skin/in-content/common-shared.css".

![aboutconfig](https://user-images.githubusercontent.com/39375837/196724767-94d92c0c-b503-4cdd-9c62-102fbf6cc476.jpg)

**Comment by xiaoxiaoflood** [comment]
Fixed, update your `chrome/utils/aboutconfig/config.js`.
