### ISSUE TITLE
Savefileto Sub-folders with "Variable" Folder Doesn't Work

### ISSUE THREAD

**Issue by megamorphg** [xiaoxiaoflood/firefox-scripts#197]
Just a quick report on something low priority, the variable seems to work fine but creating a folder using the variable doesn't work as shown below:
![image](https://user-images.githubusercontent.com/1782353/197367370-b9a8f615-b431-4bb3-b52d-2924b4c6959a.png)

Anyway, can still hard-code the full folder path but it but it would be cool to be able to in case of transferring settings between profiles on different computers.

**Comment by xiaoxiaoflood** [comment]
Thanks for reporting. Fixed in the new version I just uploaded.
