### ISSUE TITLE
DownThemAll! Toolbar icon double action

### ISSUE THREAD

**Issue by almtst** [xiaoxiaoflood/firefox-scripts#210]
When you right click on the Downthemall! toolbar icon and select any of the three menu options, the selected option (e.g., Manager) will open along with the file section window for the current tab, as if you had left clicked on the icon at the same time.

**Comment by xiaoxiaoflood** [comment]
Thanks for reporting. Fixed in the new version I just uploaded.

**Comment by almtst** [comment]
Hello, thanks for paying attention to this issue, unfortunately the fix seems to have introduced a new problem, now if you right click the toolbar icon in a new window, the default FF menu opens instead of the DTA one, this also happens right after opening FF for the first time, the problem goes away if you open the file section window by left clicking the DTA icon once, after closing it the right click menu will work as intended, but only for the current window.

**Comment by xiaoxiaoflood** [comment]
Sorry for being late, but I confirmed the issue you described and fixed it.
