### ISSUE TITLE
MinMaxClose button is not supporting dark mode

### ISSUE THREAD

**Issue by patrik-krajcovic2** [xiaoxiaoflood/firefox-scripts#214]
Actual results:
With dark mode enabled, the MinMaxClose button is black.

Expected results:
With dark mode enabled, the MinMaxClose button should be white.

Environment:
Windows 11 22621.963, 64-bit
Firefox 108.0.1

**Comment by patrik-krajcovic2** [comment]
Can you test this change? Because after updating that .js file in my chrome folder, I got this: 

![Broken MinMaxClose button](https://user-images.githubusercontent.com/69351811/209459484-966f13c7-e451-454c-bdc2-910d0f5ba27f.png)

**Comment by xiaoxiaoflood** [comment]
> Can you test this change in your Firefox? Because after I was updating that .js file in my chrome folder, I got this:
> 
> ![Broken MinMaxClose button](https://user-images.githubusercontent.com/69351811/209459484-966f13c7-e451-454c-bdc2-910d0f5ba27f.png)

Works for me.
![image](https://user-images.githubusercontent.com/25161346/209459716-03e6729f-137b-4f6c-ace9-fa4589d8ad9f.png)

**Comment by patrik-krajcovic2** [comment]
Well, then it is issue in my side, sorry.

**Comment by xiaoxiaoflood** [comment]
If you can get reliable steps to reproduce your issue from a fresh new profile, post it here and I'll try to fix.

**Comment by patrik-krajcovic2** [comment]
Yes, I am able to reproduce it even in new profile.

**Comment by patrik-krajcovic2** [comment]
1. Create new profile
2. Open about:support and create in profile folder new folder called chrome
3. Download utils with extensions and scripts, but do not copy the scripts, but copy only utils folder and rebuild_userChrome.uc.js into chrome
4. Clear startup cache
5. Now add scripts into chrome folder
6. Clear startup cache again
7. Issue is now reproducible

**Comment by patrik-krajcovic2** [comment]
And can you tell me, where are the icons for MinMaxClose stored?

**Comment by xiaoxiaoflood** [comment]
Thanks. Now it's fixed.

> And can you tell me, where are the icons for MinMaxClose stored?

[dataURI](https://en.wikipedia.org/wiki/Data_URI_scheme)

Search for

    data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAAO0lEQVQ4jWNgYGD4jwWTBCg2gBSDSTKcYgNwGUqRzfQzAJcYxQYQBahiAE0SF7pBVEn2VHEJ/VyANQwACylDvQ9eqkEAAAAASUVORK5CYII=

in the code.

Copy the entire line above, paste it in address bar, press Enter and you'll see the icon.

**Comment by patrik-krajcovic2** [comment]
Thank you, now it is working.
