### ISSUE TITLE
S3 download installation blocked, disabled 

### ISSUE THREAD

**Issue by nollinvoyd** [xiaoxiaoflood/firefox-scripts#218]
![s3](https://user-images.githubusercontent.com/20844322/209716916-a4ef64a0-2f0e-44ba-bd4b-a8fa93cda4d6.png)

![s3-2](https://user-images.githubusercontent.com/20844322/209717137-945bd6bd-bc39-4f03-badd-c2ef56116379.png)

**Comment by xiaoxiaoflood** [comment]
You probably didn't update files to latest version. Redo the instructions from main page.

**Comment by nollinvoyd** [comment]
I've updated al files, read & followed all instructions on the main page and the video; updated the default folder files and config.js files for the installation folder and updated the chrome folder files., 

I currently have three config.js files, with sizes of 570 bites (oldest - original file), and 2 others which I just downloaded;  856 bites, and 159 kb, which replaces the old config.js in N:\FIREFOX\A_ALL+++\CHROME\utils\aboutconfig\config.js.

I replaced the old 570 bites config.js with the later 856 bites config.js filer in the installation folder, cleared the startup cache and restarted, but I still get that get the "corrupt" error.  I tried putting that 159 kb config.js in the install folder, but all I got was this, which I guess was expected.
 
![config js error](https://user-images.githubusercontent.com/20844322/209870685-a79e48ed-19e7-4a24-a284-d0495d1394c0.png)

Here's my chrome folder

![chrome folder](https://user-images.githubusercontent.com/20844322/209871220-a08adb2c-ff5a-4d6f-bd64-258f130a62f9.png)

To further test, I also tried to install dta.xpi, and got the same error message

Everything else seems to be working ok

**Comment by peterwx** [comment]
Does your chrome folder belong to the intended Firefox profile? Maybe you have done changes to another profile without noticing.

**Comment by nollinvoyd** [comment]
"A_ALL+++" is just the name of my primary profile folder.  All the other components of the chrome folder operate as expected 

Everything was in place and working before the S3 download update caused it to be disabled by Firefox, it should have been just a matter of replacing the outdated files, which I did.  Or thought I did.  I either missed something or there's another issue.

I went over & over those update instructions.  Perhaps someone could post a simple list of the files that need to be replaced and where?

**Comment by xiaoxiaoflood** [comment]
Hi, I hope you managed to fix the issue you faced, it's working fine for me and others. Please make sure to use latest version of files and then restart using `Clear startup cache…` button in `about:support` page.

**Comment by nollinvoyd** [comment]
> Hi, I hope you managed to fix the issue you faced, it's working fine for me and others. Please make sure to use latest version of files and then restart using `Clear startup cache…` button in `about:support` page.

Hello again xiaoxiaoflood,

I just did a successful install with the undated 8/19 files, including the replacement of the update.rdf in the chrome folder.  I hope that was correct.

One Problem.  I have the same settings interface issue that I faced and, if I recall correctly, reported years ago.  

My desktop toolbar is at the top of the screen.  The s3 download settings interface hides under my toolbar at the top, and is also hidden off screen at the bottom.

Thus, I cannot access any of the controls in either area, unless I was to move the toolbar every time I need to access the settings.

The problem is that the interface is not resizable.  Can something be done about this?

**Comment by xiaoxiaoflood** [comment]
1. S3D prefwindow has always been big. I don't intend to change original visual aspects of extensions (and I would be a bad person to do that, I can't style properly). The most I can do, and did it now, was to reduce some vertical margins to reduce windows height. Can't say if it will be enough for you, but that's what I can do.

3. I already talked about this subject with you in other issue. S3D toolbar button isn't displayed by default when downloads list is empty. If you want to force it, open S3D settings, `General` tab, `Statusbar Mode` sub-tab, select `Auto Mode` and uncheck `hide Mini Mode icon when download list is empty`.

**Comment by xiaoxiaoflood** [comment]
It makes no sense to download update.rdf, it wasn't told to do that, there's no purpose in doing that.

If install is failing for you, you probably missed to update some files. You should repeat instructions from readme, carefully. When you finish, you install the addon as instructed in [extensions](https://github.com/xiaoxiaoflood/firefox-scripts/tree/master/extensions#instructions) page.

**Comment by nollinvoyd** [comment]
> It makes no sense to download update.rdf, it wasn't told to do that, there's no purpose in doing that.
> 

It's a bit confusing.  I asked because when I went to [https://github.com/xiaoxiaoflood/firefox-scripts/tree/master/extensions/S3Download](url), the **last commit date** for **both** the s3download.xpi and update.rdf files lists them as only "two days old", and the **Last commit message** is "s3d: reduce prefwindow height", so I thought that indicated the older versions needed to be replaced.  

>
> If install is failing for you, you probably missed to update some files. You should repeat instructions from readme, carefully. When you finish, you install the addon as instructed in [extensions](https://github.com/xiaoxiaoflood/firefox-scripts/tree/master/extensions#instructions) page.
>

Done.  Thanks.

One more question please.  I believe the complete utils folder goes into the Chrome folder, not just it's contents, correct?

**Comment by xiaoxiaoflood** [comment]
Supposing you already had the extension installed, you update it by opening about:addons, clicking the gear button then "Check for updates". What you need to manually update are only the files you download by following the [instructions](https://github.com/xiaoxiaoflood/firefox-scripts#instructions).

> https://github.com/xiaoxiaoflood/firefox-scripts#instructions

Yes. One filepath example is `<profilefolder>/chrome/utils/BootstrapLoader.js`.
