### ISSUE TITLE
FF 73 seems fine without general.config.sandbox_enabled set to false

### ISSUE THREAD

**Issue by glitsj16** [xiaoxiaoflood/firefox-scripts#22]
Hi, just a FYI: firefox 73.0b3 loads custom user scripts just fine without

`pref("general.config.sandbox_enabled", false);`

I haven't found an official URL on Mozilla/MDN (yet) that documents this change, but it works nonetheless. Might give users a more relaxed feeling knowing that nothing relating to the FF sandbox needs to be disabled...

**Comment by ganego** [comment]
At least my mousegestures also work in FF72 without this pref set (checked in about:config after removing the line from the file).

**Comment by hg42** [comment]
sorry for asking, I am just new to FF>=72 ... I used the XBL method before...

"just fine" means with adding config.js etc. to the installation folder?
and only Nightly? or also Beta?

I copied all my CSS-files into userChrome.css, which works, but @import does not.
My scroll bar agent sheet does not work, or may be I am missing something.
I also want to load development versions of some add-ons, something like:
AddonManager.installTemporaryAddon(new FileUtils.File("/path/to/extension-git/src"));

Which way is currently recommended to make all this working?

**Comment by ganego** [comment]
@hg42 You might get more answers on https://www.reddit.com/r/FirefoxCSS/

**Comment by hg42** [comment]
@ganego thanks...
I tend to ask people saying "it works!"...it's probably not the ideal place to ask such a broader question, but I intended to ask the first part about "just fine", the rest is context

**Comment by glitsj16** [comment]
> "just fine" means with adding config.js etc. to the installation folder?
> and only Nightly? or also Beta?

@hg42 The instructions aren't changed, just the one pref in [config-prefs.js](https://github.com/xiaoxiaoflood/firefox-scripts/blob/master/installation-folder/config-prefs.js). I've only tested with FF71, FF72 and FF73.0b3 (on both Arch Linux and Ubuntu 16.04 LTS).

**Comment by hg42** [comment]
@glitsj16 thanks...I didn't notice your "73.0b3" in the first comment, it already answered the "nighly or beta" question. I am on 73.0b3 on a Debian/Ubuntu mix.

**Comment by xiaoxiaoflood** [comment]
That's because you are using Developer Edition.

Fx release and Beta need this pref since [bug 1455601](https://bugzilla.mozilla.org/show_bug.cgi?id=1455601). And when [bug 1514451](https://bugzilla.mozilla.org/show_bug.cgi?id=1514451) is fixed, there will be no way to run autoconfig.js on these channels.

If you want userChromeJS, you need unsandboxed autoconfig. It's just that in DevEd, Nightly and ESR autoconfig is unsandboxed by default.

**Comment by glitsj16** [comment]
@xiaoxiaoflood Thanks for clearing that up. I'll patch out the pref locally and close this non-issue. Apologies for the noise.

**Comment by ganego** [comment]
@xiaoxiaoflood I was under the impression all this scripting only works on Developer/Nightly version - so it also works on Release?  
So is it actually more safe to use the Dev//Nightly version since we can have sandbox enabled?

**Comment by xiaoxiaoflood** [comment]
> so it also works on Release?

Yes. Current scripts and extensions in this repo are tested and working in Fx 70, no matter the channel (release, Beta, DevEd, Nightly or unbranded).

> So is it actually more safe to use the Dev//Nightly version since we can have sandbox enabled?

No, read my previous comment. Sandboxed autoconfig means "your autoconfig file can only set prefs (just like user.js file), it can't execute scripts". There is no userChromeJS or legacy addons if autoconfig sandbox is enabled.
