### ISSUE TITLE
PrivateTab button with Firefox UI Fix installed have wrong shape

### ISSUE THREAD

**Issue by Patricek0056** [xiaoxiaoflood/firefox-scripts#225]
When I have installed “Firefox UI Fix” (https://github.com/black7375/Firefox-UI-Fix), then added “Open a new private tab” button right next to right “Open a new tab” button, then the “Open a new private tab” button have wrong shape (The shape of “Open a new private tab” button is wrong but the shape of “Open a new tab” button is right). In short “Firefox UI Fix” is not supported in “Firefox scripts”.

I will attach two screenshots for better understanding:

Open a new tab button have right shape.
![Right button shape](https://user-images.githubusercontent.com/69351811/210046150-a300afc6-a18b-4e6d-a395-ca77a32f5821.png)

Open a new private tab button have wrong shape.
![Wrong button shape](https://user-images.githubusercontent.com/69351811/210046168-583887a0-b6f2-4016-b374-2877575780ec.png)

If it is this issue with “Firefox UI Fix” and not the “Firefox scripts”, then I should file a bug in “Firefox UI Fix” bug tracker instead (But I think that I am in the right place, so I reported it here).

**Comment by krystian3w** [comment]
IMO this is feature request for “Firefox UI Fix” - CSS is injected on `#tabs-newtab-button` and "only" Google duplicate ID in (x)html5.

**Comment by Patricek0056** [comment]
> IMO this is feature request for “Firefox UI Fix” - CSS is injected on `#tabs-newtab-button` and "only" Google duplicate ID in (x)html5.

Fine, I will soon close this as not planned, and post feature request for Firefox UI Fix.
