### ISSUE TITLE
Master Password+: Password pop-up appears

### ISSUE THREAD

**Issue by Patricek0056** [xiaoxiaoflood/firefox-scripts#237]
### Actual results:
When I'm going to enter my password, then a pop-up appears. That pop-up is a duplicate of Master Password+ screen.

### Expected results:
The pop-up shouldn't appear.

### Screenshots:
![Password Pop-up](https://user-images.githubusercontent.com/69351811/213903702-a329f887-8b94-424a-9ae0-44d37350262b.png)

**Comment by xiaoxiaoflood** [comment]
I guess MP+ can't control this, the popup is triggered by Firefox itself. hardcoded. What MP+ can do, and it does, is to unlock Fx when you type the password in the popup, not demanding you to type it twice.
