### ISSUE TITLE
userChromeJS Manager button broken in Firefox 110.0

### ISSUE THREAD

**Issue by nollinvoyd** [xiaoxiaoflood/firefox-scripts#242]
The button is still on the menubar, but it doesn't work.  Still works in Fx 109.01

**Comment by Patricek0056** [comment]
So you think, that is not clickable?

**Comment by Patricek0056** [comment]
Also, you have issue in the bug description, not menubar but toolbar.

**Comment by xiaoxiaoflood** [comment]
Already fixed a month ago. userChromeJS and scripts don't have autoupdate, so you need to manually download the latest version of files and replace them in your profile folder. In this case, *rebuild_userChrome.uc.js*.
