### ISSUE TITLE
CSS copied from usercontent.css into Styloax script breaks 

### ISSUE THREAD

**Issue by mzso** [xiaoxiaoflood/firefox-scripts#247]
So I copied my content of usercontent.css into a Styloaix script (using FF dev109). It consisted mostly of imports for [Custom CSS tweaks for Firefox v4.2.8](https://github.com/Aris-t2/CustomCSSforFx/releases/tag/4.2.8). I didn't change anything other than fixing the paths. But still somehow something got broken.

The items in the various categories in about:config are borked for example:
![kép](https://user-images.githubusercontent.com/4479090/220710063-6f7520bb-01d7-4e46-b876-4a96e6d07e17.png)
![kép](https://user-images.githubusercontent.com/4479090/220710225-1ca6e3a1-58fa-4f23-a05b-336e42628df9.png)

I narrowed it down to these two lines that work perfectly when used from usercontent.css
```
@import "../CustomCSSforFx/css/aboutaddons/addonlists_compact.css"; /**/
@import "../CustomCSSforFx/css/aboutaddons/addonlists_show_buttons_instead_of_menu_popup_compact_view.css"; /**/ /* for addonlists_compact.css */
```
(I have the whole package in chrome/CustomCSSforFx)

The CSS is supposed to make the list more compact and show buttons, but something goes awry.

**Comment by xiaoxiaoflood** [comment]
For `userContent.css`, you should try to register the style as `USER_SHEET`.

![image](https://user-images.githubusercontent.com/25161346/220954908-c8f8aee0-b29c-4bbb-955e-ddb3c030ac68.png)

(This topic is more suitable for [Discussions](https://github.com/xiaoxiaoflood/firefox-scripts/discussions) as it's not an actual issue in the script but a support request.)

**Comment by mzso** [comment]
Thanks!
I'm scratching my head, because I'm quite sure I tried it multiple times. And it didn't work, so I thought it was a bug.
But it works now...
