### ISSUE TITLE
Question: Any UserScript Loader ? Compatible with FF 72+

### ISSUE THREAD

**Issue by Mitezuss** [xiaoxiaoflood/firefox-scripts#26]
Hi, can implement this feature for rebuild_userChrome.js ? or is there any alternative ?

regards

Note: user.js from GreaseMonkey

**Comment by xiaoxiaoflood** [comment]
> or is there any alternative ?

[Violentmonkey](https://addons.mozilla.org/firefox/addon/violentmonkey/).
