### ISSUE TITLE
[Bug] 'Save File To' extension suffering graphical glitches

### ISSUE THREAD

**Issue by TFWol** [xiaoxiaoflood/firefox-scripts#262]
[**Save File To**](https://github.com/xiaoxiaoflood/firefox-scripts/tree/master/extensions/savefileto) extension has the same type of graphical issues as found in #246 

Options Screen (not resizable)
![image](https://github.com/xiaoxiaoflood/firefox-scripts/assets/9045213/5d84332f-1562-4800-b42c-5d5e7fa6a8ca)

**Comment by dimdamin** [comment]
try it [savefileto-2.5.6.111.2023.06.04-xiao.xpi.zip](https://github.com/xiaoxiaoflood/firefox-scripts/files/11646427/savefileto-2.5.6.111.2023.06.04-xiao.xpi.zip), i`m try 102 and 114....

**Comment by TFWol** [comment]
Thank you, it works! 
I like your workaround; throw in some `||` logic for a bandaid solution. All that matters is that it functions 😃

**Comment by xiaoxiaoflood** [comment]
Sorry for being late, but this is fixed.

**Comment by TFWol** [comment]
@xiaoxiaoflood Holy crap, you're alive!?
I really thought something may have happened to you; I've had a lot of my fav devs die recently...
