### ISSUE TITLE
TMP is disabled in Firefox 115b2.

### ISSUE THREAD

**Issue by halt76** [xiaoxiaoflood/firefox-scripts#263]
TMP is disabled in Firefox 115b2 because the certificate cannot be verified.
![Image1](https://github.com/xiaoxiaoflood/firefox-scripts/assets/105223920/e0546e22-e3af-45ac-a907-baca88201c1f)

**Comment by halt76** [comment]
Does that mean it's no longer work in the regular version?

**Comment by marty60** [comment]
> Does that mean it's no longer work in the regular version?

Has it worked in regular betas and releases for you in the past? I only use nightlies, esrs and occasionally developer betas normally where these addons have never been a problem. It was my understanding that they didn't work in regular releases and betas but maybe that's changed. 

All I can advise is try the developer beta and see if TMP is restored. 115.0 is the next esr so it should keep working in that version if there's nothing wrong with the addon itself.

**Comment by marty60** [comment]
> Does that mean it's no longer work in the regular version?

Has it worked in regular betas and releases for you in the past? I only use nightlies, esrs and occasionally developer betas normally where these addons have never been a problem. It was my understanding that addons where certificate verification was lacking were disabled in regular releases and betas but maybe that's changed.

All I can advise is try the developer beta and see if TMP is restored. 115.0 is the next esr so it should keep working in that version if there's nothing wrong with the addon itself.

**Comment by dimdamin** [comment]
> TMP is disabled in Firefox 115b2 because the certificate cannot be verified.

try this [code](https://github.com/xiaoxiaoflood/firefox-scripts/commit/66e896ec1514499557b64ce205104b04cdb8444a#diff-6ce693872e34c9b16945c043cb735f1182ccad9babda50b7a976704373e52665R11), or use original [code](https://forum.mozilla-russia.org/viewtopic.php?pid=802045#p802045) for signing bypass
after apply need remove TMP from extensions folder and reinstall again.

**Comment by halt76** [comment]
> try this [code](https://github.com/xiaoxiaoflood/firefox-scripts/commit/66e896ec1514499557b64ce205104b04cdb8444a#diff-6ce693872e34c9b16945c043cb735f1182ccad9babda50b7a976704373e52665R11)

It seems to be working properly.
Thanks.
