### ISSUE TITLE
multifoxContainer: Not working

### ISSUE THREAD

**Issue by Massimo-B** [xiaoxiaoflood/firefox-scripts#269]
I started trying some of your scripts, but multifoxContainer doesn't seem to work
```
$ cd ~/.mozilla/firefox/*default/chrome/;ls -1 *uc*
extensionOptionsMenu.uc.js
extensionsUpdateChecker.uc.js
multifoxContainer.uc.js
rebuild_userChrome.uc.js
```
Left Click on the container button inside the address bar does switch the container. Middle Click does nothing. CTRL+T just always opens a new tab without specific container.
In the container settings I have enabled _[x] Select a container for each new tab.

I'm on Firefox www-client/firefox-bin-115.0.2, Gentoo.

**Comment by xiaoxiaoflood** [comment]
There was a change in Fx 113 requiring a fix. It's working now with Fx 130. Sorry for being late.
