### ISSUE TITLE
Fast Tab Switcher not Working on 117

### ISSUE THREAD

**Issue by megamorphg** [xiaoxiaoflood/firefox-scripts#278]
As found on [this comment](https://github.com/xiaoxiaoflood/firefox-scripts/issues/265#issuecomment-1714449814), after updating to the latest program and utils files... Fast Tab Switcher has an unsave-able screen and no way trigger the shortcut:
![267125596-7cf362da-8950-4a8b-92b3-261a78a4b7fe](https://github.com/xiaoxiaoflood/firefox-scripts/assets/1782353/7624d5eb-9b31-4bea-ad9e-64b8f24a4651)

**Comment by dimdamin** [comment]
It work for me
[tabswitcher-1.0.12.95.2023.09.13-xiao.xpi.zip](https://github.com/xiaoxiaoflood/firefox-scripts/files/12610013/tabswitcher-1.0.12.95.2023.09.13-xiao.xpi.zip)
