### ISSUE TITLE
Pullrequest to dorando-keyconfig

### ISSUE THREAD

**Issue by white-gecko** [xiaoxiaoflood/firefox-scripts#28]
As it seems you have figured out how to make the dorando-keyconfig working in latest thunderbird versions. Would you consider to submit a pull-request to: https://github.com/trlkly/dorando-keyconfig/pulls ?

**Comment by xiaoxiaoflood** [comment]
[TB is removing support for legacy extensions](https://developer.thunderbird.net/add-ons/tb78). Someone could convert keyconfig to WebExt Experiments.

I don't know if _my_ keyconfig works in TB, I don't even know if TB supports autoconfig.js. If it works, great. But sorry, I don't plan to support TB. Keeping up with Fx changes is already too much for me (current DevEd is 74 and I'm still using 70).

**Comment by white-gecko** [comment]
Ok, I misunderstood some things here.
