### ISSUE TITLE
History and bookmarks are not available with Enter Selects

### ISSUE THREAD

**Issue by jmighion** [xiaoxiaoflood/firefox-scripts#280]
I'm on FF 117.0.1, updated the utils mentioned in https://github.com/xiaoxiaoflood/firefox-scripts/issues/265, redid the whole install from fx-folder.zip and utils_scripts_only.zip, then reinstalled enterSelects.uc.js. This got the usChromeJS Manager back and Enter Selects works in that it picks the correct url or suggestion, but none of the history or bookmarked urls show up when typing.
Loading FF in troubleshooting mode, the url bar will use history and bookmarks, but no Enter Select.

Did I do something wrong or is there potentially a bug here? I'm more than willing to provide more info, I would just need to know what would be helpful.

Attaching a couple of pics to show the dates on the new/updated files compared to the originals.

/Applications/Firefox.app/Contents/Resources/
![Screenshot 2023-09-17 at 4 06 06 PM](https://github.com/xiaoxiaoflood/firefox-scripts/assets/394942/826f603d-3c76-4af1-b774-c2d934f48d13)

/Users/jmighion/Library/Application Support/Firefox/Profiles/l7flkc9r.default-release/chrome/
![Screenshot 2023-09-17 at 4 05 42 PM](https://github.com/xiaoxiaoflood/firefox-scripts/assets/394942/88264d3a-5e96-4c10-8624-e930c904b0d5)

**Comment by xiaoxiaoflood** [comment]
Thanks for reporting and sorry for the late response. I just pushed https://github.com/xiaoxiaoflood/firefox-scripts/commit/4b0799f71b84fea93cdd6c38e8ffe94e2542cef8 to fix this issue. I hope it's working for you now.
