### ISSUE TITLE
Tab Groups no longer working after update

### ISSUE THREAD

**Issue by Ofunniku** [xiaoxiaoflood/firefox-scripts#292]
I had kept my Firefox at 114 for awhile because updates kept breaking the addons, and would update manually, but I've been busy and completely forgot.

After updating to 120, I found most of my legacy extensions stopped working, so I grabbed the versions of `fx-folder.zip` and `utils_extensions_and_scripts.zip` from Tab Mix Plus and things seem to work fine now, but Tab Groups no longer work. (from https://github.com/117649/Tab-Groups/releases/latest)

Any chance we can get this working again?

**Comment by 117649** [comment]
It should work if you download the source code and pack the .xpi and install by yourself.
It so easy just pack everything into a .zip and change the extension name. 
I should have left a ```pack.ps1``` script there you can run it with PS version higher than 7 and it should done everything for you. 
There just so little users I'm no longer bother to upload a new release anymore.

**Comment by Ofunniku** [comment]
Thank you, it works fine now.

Yeah, I honestly believe that this feature was never given a fair shot by Mozilla when they added it.
