### ISSUE TITLE
StyloaiX editor does not work correctly in Firefox 122

### ISSUE THREAD

**Issue by srjjgm** [xiaoxiaoflood/firefox-scripts#294]
1) The editor's "useful area" is narrower than the window.
2) Autocomplete suggestions are not shown.
3) Line break separates "!important", isolating the exclamation mark.
Some help?

**Comment by 117649** [comment]
Tried fix 1 & 2, no idea about 3 yet.
Replace the folder in ```utils```.

[styloaix.zip](https://github.com/xiaoxiaoflood/firefox-scripts/files/13761131/styloaix.zip)

**Comment by srjjgm** [comment]
It worked! Thank you very much!
It seems to me that the editor separates any word that contains characters like "!", "-" or "."
Maybe it's a change from version 122, I don't know. If you find a solution I will greatly appreciate it.
Have a happy Christmas!

**Comment by srjjgm** [comment]
I found a "solution" for separating words and characters. Actually, it's just a CSS code that minimizes the problem, until the correct solution appears:
<@-moz-document url-prefix("chrome://userchromejs/content/styloaix/edit") {
.CodeMirror pre.CodeMirror-line > span > span:is(.cm-keyword, .cm-variable-2, .cm-number)
{
white-space: nowrap
}
}>

**Comment by srjjgm** [comment]
I found a "solution" for separating words and characters. Actually, it's just a CSS code that minimizes the problem, until the correct solution appears:

<code>@-moz-document url-prefix("chrome://userchromejs/content/styloaix/edit") {
.CodeMirror pre.CodeMirror-line > span > span:is(.cm-keyword, .cm-variable-2, .cm-number)
{
white-space: nowrap
}
}</code>
