### ISSUE TITLE
status-bar.uc.js - Doesn't work anymore

### ISSUE THREAD

**Issue by AtTheGates** [xiaoxiaoflood/firefox-scripts#30]
Hello,

it seems, that this script doesn't work anymore. I testet it with FF v74 and v68.6 ESR (under Windows 10). There is no entry under the toolbars menu. If you have the time, could you take a look at this?

Thank you in advance. :-)

Greets

**Comment by xiaoxiaoflood** [comment]
You can see current compatibility in Readme, it's always based on the version I'm using. Now I'm on Fx 72 and hopefully I will update soon to Fx 75 (current DevEd).

I don't work to keep backward compatibility, for that you should see [version history](https://github.com/xiaoxiaoflood/firefox-scripts/commits/master/chrome/status-bar.uc.js), there must be a version compatible with 68. If I remember corretly, at that time I hadn't yet implemented entry under toolbars menu, the only way to hide statusbar was disabling the script, but maybe versions from december/january (Fx 69/70) work with 68ESR.

But to downgrade to 68 you need to downgrade the `utils` folder too, especially `userChrome.jsm`.

**Comment by AtTheGates** [comment]
I'm so sorry! It seems, that I used older or corrupted **.jsm** files. After downloading the **utils** folder again, it's working without any problems now. With release FF v74 AND v68 ESR.

Usually I doublecheck all sources of error. I'm really embarrassed. Again... sorry and thank you for your work with the scripts.

Do you delete this "issue" or should I do?
