### ISSUE TITLE
Again, the private tabs script stopped working (from Firefox 123 onwards).

### ISSUE THREAD

**Issue by kaos-55** [xiaoxiaoflood/firefox-scripts#301]
As the title says, the script stopped working again as it did last time https://github.com/xiaoxiaoflood/firefox-scripts/issues/290 Now the problem, unlike last time, is that the button does not even appear. Again I open another problem, if someone has a solution to make it work again it would be appreciated.

**Comment by dimdamin** [comment]
Hi @kaos-55.
can you provide any step for reproduce?

**Comment by kaos-55** [comment]
Hi @dimdamin I'm sorry but I don't understand what you mean by steps to reproduce it. The only thing I did was to install the userChromeJS along with the script as it says on the main page in a fresh installation of firefox.
I even installed another script to verify that the userChromeJS would actually work, but when I installed the script the new private tab button does not appear in the toolbar or in the tab bar.

**Comment by kaos-55** [comment]
@dimdamin Thanks
I followed the guide you provided and the script works. I don't know why last time it didn't work for me maybe because I had an outdated version of userChromeJS.

**Comment by YousufSSyed** [comment]
@dimdamin Where did u get this private script from?

**Comment by dimdamin** [comment]
@YousufSSyed you can flow to...

**Comment by YousufSSyed** [comment]
@dimdamin huh? I asked where dud u get the private tab script from.

**Comment by dimdamin** [comment]
@YousufSSyed 

>  I asked where dud u get the private tab script from.
from this.

**Comment by kaos-55** [comment]
I close this issue since the script is now working except for a small bug found https://github.com/xiaoxiaoflood/firefox-scripts/issues/308
