### ISSUE TITLE
minmaxclose script not working on new 126.0 FF

### ISSUE THREAD

**Issue by momo1958** [xiaoxiaoflood/firefox-scripts#304]
Hello,

**minmaxclose** script not working entirely on latest 126.0 FF; left-click does minimize it but right-click no longer exits browsser

**Comment by dimdamin** [comment]
Hello,
need to replace, try:
 ```diff
-win.BrowserTryToCloseWindow();
+win.BrowserCommands.tryToCloseWindow();
```

**Comment by momo1958** [comment]
> Hello, need to replace, try:
> 
> ```diff
> -win.BrowserTryToCloseWindow();
> +win.BrowserCommands.tryToCloseWindow();
> ```

YES! Thanks a lot! :-)
