### ISSUE TITLE
Extensions Update Checker stopped working recently

### ISSUE THREAD

**Issue by nollinvoyd** [xiaoxiaoflood/firefox-scripts#307]
That's about it.  Just stopped reporting updates about a week ago.  I have the latest version. 

https://github.com/xiaoxiaoflood/firefox-scripts?tab=readme-ov-file

**Comment by dimdamin** [comment]
```Diff
-    const { AddonManager, BrowserOpenAddonsMgr } = Services.wm.getMostRecentBrowserWindow();
+    const { AddonManager, BrowserAddonUI } = Services.wm.getMostRecentBrowserWindow();

-      BrowserOpenAddonsMgr('addons://updates/available');
+      BrowserAddonUI.openAddonsMgr('addons://updates/available');
```
tested in 128b4

**Comment by nollinvoyd** [comment]
Like this?

observe: async function () {
    const { AddonManager, BrowserAddonUI } = Services.wm.getMostRecentBrowserWindow();
    let addons = await AddonManager.getAllAddons();
    if (addons.some(addon => addon.updateInstall && !this.ignoreList.includes(addon.name)))
      BrowserAddonUI.openAddonsMgr('addons://updates/available');
  },
``

**Comment by nollinvoyd** [comment]
Like this?

observe: async function () {
    const { AddonManager, BrowserAddonUI } = Services.wm.getMostRecentBrowserWindow();
    let addons = await AddonManager.getAllAddons();
    if (addons.some(addon => addon.updateInstall && !this.ignoreList.includes(addon.name)))
      BrowserAddonUI.openAddonsMgr('addons://updates/available');
  },
``
> tested in 128b4

How did you test it?  I installed a previous version of one of my addons, but I don't know if it only works for updates that were just released, or how long it takes to do it's job.

**Comment by dimdamin** [comment]
> How did you test it?

If you have addon update, this script open about:addons page and switch to Available Updates.

**Comment by nollinvoyd** [comment]
It works.  Thanks!

**Comment by nollinvoyd** [comment]
The changes by @dimdamin corrected the problem.

**Comment by Avrution** [comment]
Doesn't seem to be working in 115 even with the changes.  Is there a way to manually test the script?
