### ISSUE TITLE
A small bug in private tab script. Private tabs button disappears inside the tab bar when the tab bar is full instead of staying in place.

### ISSUE THREAD

**Issue by kaos-55** [xiaoxiaoflood/firefox-scripts#308]
When the private tab button is placed in front of the new tab button in the tab bar, it disappears as soon as the tab bar is full. To access the private tabs button, scroll to the last tab.

-Install de private tab script.
-Move the private tab script in front of the new tab button in the tab bar.
-Open many tabs until the tab overflow arrows appear.
-The private tabs button disappears and is located at the end of the last tab.

Fortunately, this bug does not affect the functionality of the script, although it is a bit annoying.
I tried to look for a solution but I did not achieve anything, if someone knows a way to fix it, I would appreciate it.

https://github.com/xiaoxiaoflood/firefox-scripts/assets/86812371/d0b60412-52ab-4a67-8570-9edc41be8128

**Comment by dimdamin** [comment]
Hi, you can modify embedded css
```Diff
-          #tabbrowser-tabs[hasadjacentnewprivatetabbutton]:not([overflow="true"]) ~ #${UC.privateTab.BTN_ID},
-          #tabbrowser-tabs[overflow="true"] > #tabbrowser-arrowscrollbox > #tabbrowser-arrowscrollbox-periphery > #${UC.privateTab.BTN2_ID},
+          #tabbrowser-tabs[hasadjacentnewprivatetabbutton]:not([overflow]) ~ #${UC.privateTab.BTN_ID},
+          #tabbrowser-tabs[overflow] > #tabbrowser-arrowscrollbox > #tabbrowser-arrowscrollbox-periphery > #${UC.privateTab.BTN2_ID},

```

**Comment by kaos-55** [comment]
it´s working thank you so much.
I left the updated script in case someone else finds it useful or wants to use it.
[privateTab.uc.zip](https://github.com/user-attachments/files/16033250/privateTab.uc.zip)
I am leaving the issue open for a while so that it has more visibility in case someone has the same problem with the script and is looking for a solution.
