### ISSUE TITLE
Tab focus

### ISSUE THREAD

**Issue by Orriky** [xiaoxiaoflood/firefox-scripts#31]
Tab Focus is an old extension that works well on Waterfox Current 2020.04.
It gives focus at the Tab on which there is the mouse pointer.
It can also be installed in Firefox Developer thanks to your scripts. Unfortunately the extension doesn't work on Firefox. I'm confident that only few adaptions are needed to make it working again.
https://www.mediafire.com/file/jga4nwhq8s566v1/tab_focus-2.0.3-fx.xpi

**Comment by xiaoxiaoflood** [comment]
Hi.

Sorry, I have no plan to fix other legacy extensions beside those currently in the repository.
