### ISSUE TITLE
Now addons from Firefox Add-ons can't be installed with extension signature check disabled under mozilla's new practice!

### ISSUE THREAD

**Issue by 117649** [xiaoxiaoflood/firefox-scripts#310]
@xiaoxiaoflood Looks like you're back from dead! Is that real? If its true that's very good!

Back to the business, In short we found Mozilla no longer include decoded extension id in the .xpi files on their add-ons site.
The id have to be decoded from signature when its been checked.
This effectively prevent add-ons from Mozilla been installed with extension signature check disabled by user.
So the scripts have to be update accordingly. 

Here is how we first found this out:
https://github.com/onemen/TabMixPlus/discussions/292
https://github.com/onemen/firefox-scripts/pull/1#pullrequestreview-2040168616

Here are the files I have updated myself which have been worked for me so far.
Please use these as a reference.
[config.js.txt](https://github.com/user-attachments/files/16647416/config.js.txt)
[RDFManifestConverter.sys.mjs.txt](https://github.com/user-attachments/files/16647429/RDFManifestConverter.sys.mjs.txt)
[BootstrapLoader.jsm.txt](https://github.com/user-attachments/files/16647430/BootstrapLoader.jsm.txt)
[RDFDataSource.sys.mjs.txt](https://github.com/user-attachments/files/16647431/RDFDataSource.sys.mjs.txt)

**Comment by xiaoxiaoflood** [comment]
Hi, @117649.

Thank you for reaching out and for providing the fix. I commited your changes with very minor changes. Please let me know if there's still something to be done.

**Comment by 117649** [comment]
If you've tested the files are working then nothing else so far.

**Comment by 117649** [comment]
I'm closing this as it should be consider fixed at this point.
If anything, reopen.
