### ISSUE TITLE
DownThemAll "Set file time to last modified time (server)" is broken

### ISSUE THREAD

**Issue by jiangzhenjerry** [xiaoxiaoflood/firefox-scripts#311]
In the DownThemAll updated yesterday (welcome back btw!), "Set file time to last modified time (server)" is broken. The last modified time is not preserved, even though this option is selected.

<img width="440" alt="1" src="https://github.com/user-attachments/assets/f58e1aa0-c0ff-43b6-81ef-2a024e7d3437">

**Comment by xiaoxiaoflood** [comment]
Couldn't reproduce it, tested here and it's working as expected, with this checkbox on and off.

Maybe it only affects Windows? I use Linux.

**Comment by xiaoxiaoflood** [comment]
Well, I just tested on W11 and it's working too...

**Comment by jiangzhenjerry** [comment]
@xiaoxiaoflood I tested it in a clean Windows environment (inside Windows Sandbox) and with a clean Firefox profile. It only "sometimes" works. I cannot identify the pattern yet. The video below shows one example. What I did in the video:

1. Open Firefox, navigate to a page under https://ftp.mozilla.org/
2. Download a random file from there. **It works - the file timestamp is preserved.**
3. Keep Firefox open, create a new Private window, and navigate to the same page.
4. Download another random file from there. **This time it fails - the file timestamp is not preserved.**


https://github.com/user-attachments/assets/c4c5255e-ab4c-4d86-99ee-88a17765c7e7

**Comment by xiaoxiaoflood** [comment]
Thanks, I was able to reproduce, but in normal browsing mode, seems inconsistent, I don't know yet, will try too look at. Do you know if this is a regression from recent versions? Did it work for you in the past, like in 2022?

**Comment by jiangzhenjerry** [comment]
@xiaoxiaoflood Now that you reminded me - Yes, it did break in 2023. Actually I reported it in https://github.com/xiaoxiaoflood/firefox-scripts/issues/259#issuecomment-1566410570 and @xelsios fixed it at that time. 

Right now I am using the binary here https://github.com/xiaoxiaoflood/firefox-scripts/issues/274#issuecomment-2185363871 and it works fine, too.

**Comment by xiaoxiaoflood** [comment]
Thanks. Tested here with v111 and it was working. I will run mozregression later to try to find what caused the regression.

**Comment by xiaoxiaoflood** [comment]
Fixed version has been uploaded..
