### ISSUE TITLE
DownThemAll "Copy Links" function is broken

### ISSUE THREAD

**Issue by jiangzhenjerry** [xiaoxiaoflood/firefox-scripts#317]
See the screenshot below. In the DownThemAll window,

1. Select any number of links
2. Press `Ctrl+C`, or Right Click -> Copy Links

The links are not copied. You can confirm it by trying to paste it in Notepad - it will fail.

<img width="509" alt="1" src="https://github.com/user-attachments/assets/07178258-5a2e-4252-9d3d-766b70095ad9">

**Comment by xiaoxiaoflood** [comment]
Thanks. Fixed. It looks this is an unnoticed old bug dating back to 2015, when DTA! was still in active development by its author.

Cause:

https://bugzilla.mozilla.org/show_bug.cgi?id=1166840

**Comment by jiangzhenjerry** [comment]
@xiaoxiaoflood Thank you for the quick fix! Confirmed it is working now.
