### ISSUE TITLE
DownThemAll and S3Download

### ISSUE THREAD

**Issue by Orriky** [xiaoxiaoflood/firefox-scripts#32]
Hi,

I'd like to show files downloaded with DownThemAll in S3Download status bar.
Are you interested in adding this feature?

**Comment by xiaoxiaoflood** [comment]
Hi,

That would be hard. I don't even really know deeply how the code of these extensions work, I just provide fixes for incompatibilities from Fx updates.

So all extensions here are in maintenance mode (no new features, just fixes).

I'll let this open, but I will not work on it. If someone else is interested in doing so, this person can send the code to me and I'll include in my updates.

**Comment by hqhbaby** [comment]
why not update DownThemAll 4？

**Comment by xiaoxiaoflood** [comment]
Closing as I won't add it. I can accept pull request if someone works on it.

**Comment by K4sum1** [comment]
> That would be hard. I don't even really know deeply how the code of these extensions works, I just provide fixes for incompatibilities from Fx updates.

I don't know, you seem to have significantly changed DTA from latest master to your first release. I wanted to see about adding progress bar back but so much has changed that idk where to look.
