### ISSUE TITLE
Can I use this to cuztomize keyboard shortcuts?

### ISSUE THREAD

**Issue by jerkstore369** [xiaoxiaoflood/firefox-scripts#33]
I'm not a programmer but someone on reddit said that I can use this to edit the default keyboard shortcuts. Does that mean a compatible version of Dorando has to be made? I just want to get rid of shift-return. I keep pressing them together by accident.

**Comment by marty60** [comment]
Were you able to set this up? You can install the legacy keyconfig to change default keyboard shortcuts.

**Comment by xiaoxiaoflood** [comment]
Just read instructions and install keyconfig.
