### ISSUE TITLE
rebuild_userChrome.uc.js

### ISSUE THREAD

**Issue by Orriky** [xiaoxiaoflood/firefox-scripts#35]
Hi,

right click to edit the script does not work

**Comment by xiaoxiaoflood** [comment]
That's because Fx doesn't have a default editor anymore (Scratchpad). You need to set the path of your editor in `about:config`'s `view_source.editor.path`. Something like `C:\WINDOWS\system32\notepad.exe` if you're on Windows. I use Notepad++.

**Comment by xiaoxiaoflood** [comment]
Duplicate of #23.
