### ISSUE TITLE
styloaix not working

### ISSUE THREAD

**Issue by 117649** [xiaoxiaoflood/firefox-scripts#37]
Fx68 here and got this error message in browser console:

styloaix.uc.js
TypeError : _uc.sss is undefined styloaix.uc.js:343

**Comment by xiaoxiaoflood** [comment]
_uc.sss is defined in userChrome.jsm, be sure to always have the latest version of the file. And sorry, I won't support old Firefox versions. Everything here is made to work in Developer Edition, the version I use. Today this means Fx 78. Things may or may not work in other versions.

I'm using StyloaiX without any known bug.
