### ISSUE TITLE
Passwordmanager

### ISSUE THREAD

**Issue by MysteryIII** [xiaoxiaoflood/firefox-scripts#38]
Hello,
thanks a lot for bringing back the old password manager. I was directed here by another user.

I'm not using anything else from your Repo, so my question is what are the necessary steps to bring the password manger back?
I added the files to the Chrome folder and added the css files either to UserChrome.css and UserContent.css as I wasn't sure were to put it. However it still shows site doesn't exist when I open chrome://userchromejs/content/passwordmgr/passwordManager.xhtml

**Comment by xiaoxiaoflood** [comment]
Hi,
Just read the instructions on main page. Nothing here is related to userChrome.css or userContent.css, you seem to be mixing things up.

**Comment by MysteryIII** [comment]
If I understand it right, this is a User Chrome script like AddOn bar, Alternative Searchbar, Space and Separator Restorer and so on. Actually I'm using quite some Scripts.
As this, I have to put the files simply into chrome folder and CSS files must be loaded in UserChrome.css or User Content.css depending on how/where it works. This part is made by your StyloaiX automatically, but I don't use it, so have to import the CSS files manually.

However it doesn't really work on my profile, so I'm missing something.

And for the legacy Passwordmanager I only find the information that you brought it back and it's addressable with chrome://userchromejs/content/passwordmgr/passwordManager.xhtml
I don't see any further instruction about how to implement it.

**Comment by xiaoxiaoflood** [comment]
You must follow instructions from main page as you're interested in scripts.

At the end, save the tree passwordmanager files exactly as they are, including the path (chrome\utils\passwordmdr). There's nothing related to userChrome.css or userContent.css.

**Comment by MysteryIII** [comment]
Ah ok, so I also need the utils_scripts_only in chrome folder existing.
Would it conflict with my already used scripts or is it simply an addition?

Thanks a lot for your help!

**Comment by xiaoxiaoflood** [comment]
You seem to be using a different .uc.js loader. I can't do nothing about this. Everything here is expected to work with files from here, as instructed.

Installing my  userChromeJS loader will probably make your .uc.js files to load twice, one with my loader and other with your current loader (probably userChrome.js, which I don't use). You should use only one.

And I don't know if your loader uses a subfolder to .uc.js file. Mine doesn't, so .uc.js should be placed right into chrome folder.

**Comment by MysteryIII** [comment]
Yes you're right, [that's](https://github.com/ardiman/userChrome.js) what I'm using.

I already tried to simply add the files into chrome folder but that didn't help either. Maybe I ask elsewhere how to "port" it.

As the saying: never change a winning horse, I don't really want to change the loader, especially as I don't know if it might result in conflicts with other scripts.

**Comment by xiaoxiaoflood** [comment]
OK, closing this one as it's not really an issue, password manager is working as expected, anyone who wants to use it just needs to follow the instructions.
