### ISSUE TITLE
Request: Script to clear the search bar after the search

### ISSUE THREAD

**Issue by Haven667** [xiaoxiaoflood/firefox-scripts#40]
Hello,

first thank you very much for your work with the scripts. I use 5-6 of them already. :-)

Could you write a script which clears the search bar after the search (pressing ENTER)? Until FF v77 I used the old script [**Clear Search Word**](https://github.com/ardiman/userChrome.js/tree/master/clearsearchword) by **ardiman** with your **userChrome.js** method. Sadly it stopped working with FF v78.

Any chance that you could provide a similar script for FF v78 and above?

Thank you very much in advance.

**Comment by xiaoxiaoflood** [comment]
I don't use searchbar, but it seems that this works:
```
(function (searchbar) {
  searchbar.doSearch_org = searchbar.doSearch;
  searchbar.doSearch = function () {
    this.doSearch_org.apply(this, arguments);
    this.value = '';
    this.updateDisplay();
  }
}(document.getElementById('searchbar')));
```

**Comment by Haven667** [comment]
Thank you for the answer. The script works in the Console for me, too. But since v78 not with your **userChrome.js** (which I prefer over the other methods) anymore. I wonder why? Could you give me hint how to make it work again? That would be really nice. Thank you.

**Comment by xiaoxiaoflood** [comment]
Without digging into the issue, I bet that now the searchbar element is being created lazily, i.e. it doesn't exist when the script runs. So an easy fix would be to wait a while before running the script. For example, replace the code body (do not delete the metadata/header block) by this:
```
setTimeout(() => {
  searchbar = document.getElementById("searchbar");
	searchbar.doSearch_org = searchbar.doSearch;
	searchbar.doSearch = function(aData, aWhere, aEngine) {
		this.doSearch_org(aData, aWhere, aEngine);
		this.value = "";
		this.updateDisplay();
	}
}, 3000); // 3000ms = 3 seconds
```

You can adjust the time as you want or need.

**Comment by Haven667** [comment]
Oh yes... it really works again! Thank you so much for taking the time to help me. I really appreciate it. :-)

All the best & kind regards.
