### ISSUE TITLE
Allow hooking into devtools

### ISSUE THREAD

**Issue by Kyuuhachi** [xiaoxiaoflood/firefox-scripts#42]
Would occasionally be useful; in particular, I want to try to add a "copy as httpie" in addition to the "copy as curl". There are a few other minor ideas I've been toying with too, but have no way to implement.

I have no idea how to go about this though — the page inspector (F12) is just an iframe, but I have no idea about the browser inspector (C-S-I).

**Comment by xiaoxiaoflood** [comment]
An UCJS acting in DevTools seems to be fully possible. The difference with Browser Toolbox is that this one loads over its own profile, so you need to create all the userChrome structure (chrome folder and its files) inside `<profile-folder>\chrome_debugger_profile\`.
