### ISSUE TITLE
rebuild_userchromejs is broken

### ISSUE THREAD

**Issue by daemonspudguy** [xiaoxiaoflood/firefox-scripts#43]
According to console, this is the error:
`   NotFoundError: Node.insertBefore: Child to insert before is not a child of this node rebuild_userChrome.uc.js:277:70
    onBuild file:///home/spud/.mozilla/firefox/zz9xfriy.dev-edition-default/chrome/rebuild_userChrome.uc.js?1595178026000:277
    aEventName resource:///modules/CustomizableUI.jsm:2869
    buildWidget resource:///modules/CustomizableUI.jsm:1691
    getWidgetNode resource:///modules/CustomizableUI.jsm:1166
    buildArea resource:///modules/CustomizableUI.jsm:976
    registerToolbarNode resource:///modules/CustomizableUI.jsm:890
    registerToolbarNode resource:///modules/CustomizableUI.jsm:3606
    onDOMContentLoaded chrome://browser/content/browser.js:1792
    onDOMContentLoaded self-hosted:935`
EDIT: I have a new error code I just discovered. Here it is: `TypeError: can't access property "hidden", doc.getElementById(...) is null`

**Comment by daemonspudguy** [comment]
Got it working.

**Comment by daemonspudguy** [comment]
Brilliant. Another error. Now I get `CustomizableUI: Custom widget with id userChromebtnMenu does not return a valid node`

**Comment by xiaoxiaoflood** [comment]
It's not broken, but I can't guarantee it will work with your modifications if you use other scripts or something else. Nor if you change something in my scripts.

Current rebuild_userChrome.uc.js code should work with any Fx between 69 and 80. It probably works on Nightly (81) too, but I don't test on it as I use Developer Edition (80).

**Comment by daemonspudguy** [comment]
No other modifications are done. Everything's installed where it should be. I'm on Linux, so Firefox Developer Edition is stored in my /opt folder. Not sure if that makes a difference or not.

**Comment by daemonspudguy** [comment]
On my Mac, I cleared my startup cache and magically it worked. I've tried multiple times on Linux and nothing.

**Comment by xiaoxiaoflood** [comment]
It was really broken on Linux, sorry for denying it. Fixed by bece870.

**Comment by daemonspudguy** [comment]
I forgive you man. I firmly believe that admitting that you fucked up and
promising to do better is the best response when you learn that you made
mistakes.
