### ISSUE TITLE
Suggestion for a new userscript

### ISSUE THREAD

**Issue by ghost** [xiaoxiaoflood/firefox-scripts#46]
Hi,

I'm running flawlessly your _masterPasswordPlus.uc.js_ script / Firefox 79.0. Brilliant.

In the case you'd have spare time, wondering "what could I possibly do today?" (lol) I'd bring to your attention what may be appreciated by several of us : a cousin script to _masterPasswordPlus.uc.js_

More seriously, the idea is that of a script which would bring a toolbar button with the only purpose of toggling the activation of the Master Password.

_masterPasswordPlus.uc.js_ handles the activation/deactivation of the Master Password, the code is there to apply it to my suggestion.

The pertinence of a Master Password toggle script? The ability to carry on a browser session with the Master Password deactivated. I may wish to run Firefox without the Master Password (i.e. friends, relatives around), activate/deactivate it accordingly. At this time, lock is performed via your script with _Ctrl+Alt+Shift+W_ (but that blocks as well the use of the browser given it's the very purpose of the script), or with Firefox's _Clear All History (ctrl+shift+del) > Active Logins_ checked . I think a toggle would be pertinent that would allow to carry on a session with the Master password locked and unlock it with a click on a toolbar button (as available on Password Managers' extensions such as _Bitwarden_).

Even more seriously, I'm sure you have no time to spare, even less to lose. This is a plain suggestion, an idea, not even a concept!

Thanks for your scripts, all of 'em, and the very userChromeJS protocol installer which allows them all.

**Comment by xiaoxiaoflood** [comment]
It's possible to toggle Master Password script through rebuild_userChrome.uc.js menubutton.
