### ISSUE TITLE
How to remove/deactivate windows control buttons (min, max, close)

### ISSUE THREAD

**Issue by Altsinn** [xiaoxiaoflood/firefox-scripts#48]
Hi  @xiaoxiaoflood, 

I'm still using your hideTitlebar.uc.js script together with Tree Style Tab addon. It is super-convinient when I need to toggle a tab-bar - no need to use .css or restart a browser. However I have one issue. When the tab-bar is hidden,  windows control buttons are still present. What worse, they are active despite being covered by other buttons. So e.g. you can accidentality close the browser when you just want to open the sidebar. Is there any way to get rid off them permanently or at least to deactivate them?

![obraz](https://user-images.githubusercontent.com/50676021/90028700-4ce00900-dcba-11ea-9e82-92ea4581e1c7.png)

![obraz](https://user-images.githubusercontent.com/50676021/90028791-684b1400-dcba-11ea-936f-b86be9d39b50.png)

**Comment by xiaoxiaoflood** [comment]
This script hid window control buttons on Windows 10. Can't say about other OS.

But this script is very ugly, I was using it before knowing how to properly hide titlebar using CSS.

I suggest you to use StyloaiX + hideTitlebar.css:
```
@-moz-document url(chrome://browser/content/browser.xhtml) {

  #TabsToolbar {
    visibility: collapse;
  }

  #titlebar {
    -moz-appearance: none !important;
  }

}
```

I can toggle this style (and tabbar) just like you toggle hideTitlebar.uc.js, without needing to restart Fx or having to edit anything (I don't use userChrome.css).

But I still can't say if it will work for you the same way it does here with Windows 10.
