### ISSUE TITLE
How to use <checkbox> element in the extension pref page?

### ISSUE THREAD

**Issue by 117649** [xiaoxiaoflood/firefox-scripts#49]
I'm trying to make a pref page for an bootstrap extension but \<checkbox> elements just won't display at all, so does the label of the buttons.
What I'm missing here?

**Comment by xiaoxiaoflood** [comment]
Without further info I can't say.

But please, note that this is not a place for general support about legacy extension development, I suggest you to ask these things here:
http://forums.mozillazine.org/viewforum.php?f=19

Almost all legacy addons in this repository use checkbox customElement, so you can read and play with the codes, but you should probably use `<input type="checkbox>` instead.
