### ISSUE TITLE
[Solved] Need help loading userChromeJS

### ISSUE THREAD

**Issue by B3nji957** [xiaoxiaoflood/firefox-scripts#56]
I tried following the instructions on Github, but it didn't work for me. Can someone please make a video getting this to work?

Here is a video of what I did: https://streamable.com/phceok

**Comment by AlexVallat** [comment]
Can't do a video right now, but your first step is wrong. The instructions say to download [https://raw.githubusercontent.com/xiaoxiaoflood/firefox-scripts/master/fx-folder.zip](this zip file) and extract into Firefox folder. You downloaded the whole repo (probably from the Code button, Download Zip).

**Comment by old-izayoi** [comment]
@B3nji957 having the same issue, followed the instructions, but nothing :c

**Comment by B3nji957** [comment]
> Can't do a video right now, but your first step is wrong. The instructions say to download [this zip file](https://raw.githubusercontent.com/xiaoxiaoflood/firefox-scripts/master/fx-folder.zip) and extract into Firefox folder. You downloaded the whole repo (probably from the Code button, Download Zip).

Thank you so much! I got it to work now.

**Comment by old-izayoi** [comment]
@AlexVallat i do everything right, but it doesn't work. the fx-zip files to the firefox folder and scripts in chrome (profile folder), also tried removing the css files for the theme, but it didn't work at all, using latest dev on w10
![image](https://user-images.githubusercontent.com/47667454/96051923-2f2f4b80-0e85-11eb-96a0-a0c521b7e069.png)
![image](https://user-images.githubusercontent.com/47667454/96052356-0b203a00-0e86-11eb-850e-8f375b571408.png)

**Comment by B3nji957** [comment]
> 
> 
> @B3nji957 having the same issue, followed the instructions, but nothing :c

@old-izayoi here is a video of how I got it to work: https://streamable.com/s252bi

**Comment by B3nji957** [comment]
@old-izayoi can you show what's inside your defaults\Prefs folder as well as your utils folder?

**Comment by AlexVallat** [comment]
Looking at your screenshots, I think the deprecated folder shouldn't be there, those are scripts that are no longer in use. In general the idea is to pick the scripts you actually want to use rather than just dump everything in there! Also, styloaix.zip doesn't belong there; if you want to use styloaix you need to unzip the contents into the folder.

I would suggest clearing out the chrome folder and just putting rebuild_userChrome.uc.js (if you want to use scripts) and extensionOptionsMenu.uc.js (if you want to use extensions) and see if it works with those. If it still doesn't work, your best bet is to open the browser toolbox and scroll back up through the log and see if anything seems relevant.

**Comment by old-izayoi** [comment]
> 
> 
> @old-izayoi can you show what's inside your defaults\pref folder as well as your utils folder?
1 pic - chrome, did everything like you in the video
2 pic - def only has "pref" folder in it
still dont see anything appearing in my adressbar
![image](https://user-images.githubusercontent.com/47667454/96115011-05127380-0eef-11eb-9c1c-49964c118267.png)
![image](https://user-images.githubusercontent.com/47667454/96115172-35f2a880-0eef-11eb-8f8b-14ea5b260291.png)

**Comment by peterwx** [comment]
@old-izayoi maybe it is the wrong profile (if you have >1 profile) that you are making changes to and then running another one?.

**Comment by old-izayoi** [comment]
@peterwx using only the dev version, the other profile is old and from the default mozilla, it alsos shows me the right profile when i click on the "profile folder" button, i thought that the .css files could cause the problem, but removing them didnt help at all

**Comment by peterwx** [comment]
@old-izayoi another suggestion: try clearing the script cache manually w/ browser closed then start Firefox.
To do this go to `<profile-name>` folder inside `mozilla` folder on `appdata->local` (not the roaming folder where your profile is) then delete `startupCache` folder. After this start `FF`.
Are scripts even showing in `Browsers Toolbox` or the like under sources separator?

**Comment by old-izayoi** [comment]
@B3nji957 it's for css theme, couldn't be the problem issue.
@peterwx i deleted the folder from "local" and restarted the ff manually. nah, they arent showing up anywhere, neither the shape that controls the scripts does. i have 5 extensions pinned there, but idk if could be the problem, i still can place like 4-6 more there

**Comment by B3nji957** [comment]
@old-izayoi does your chrome\utils folder inside your profile have these files?

Also, try going to your profile folder in about:support and delete the storage folder. Start Firefox and tell me how it goes.

![2020-10-17 11_52_02-utils](https://user-images.githubusercontent.com/43734617/96347364-50ec2680-106f-11eb-9c82-197e8423a7d5.png)

**Comment by AlexVallat** [comment]
Another thing that randomly helps is deleting the chrome_debugger_profile folder in the profile. This resets the browser toolbox devtools window. No idea why that would help, or if it only helps when you've been using the toolbox for debugging, but it's worth a go.

**Comment by peterwx** [comment]
Or it could be the files (`config.js`, etc.) are placed in `FF` installation folder instead of in the `Dev FF` installation folder, which is the one used.
Maybe you could try redoing the process of placing the files in a new profile and see if that works.

**Comment by old-izayoi** [comment]
@B3nji957 
![image](https://user-images.githubusercontent.com/47667454/96353067-685bfb80-10d1-11eb-92c5-dd2ea483aec6.png)
just added all of them, i thought you should only paste the ones from utils only zip, like you did in the vid, but it didnt help, im about to try other 2 suggestions then i will install a default firefox and see what happens

**Comment by old-izayoi** [comment]
Thanks to everyone, I forgot that dev version has its own folder, thought Mozilla one is for every version
