### ISSUE TITLE
StyloaiX Cannot edit saved styles on firefox 82

### ISSUE THREAD

**Issue by benzBrake** [xiaoxiaoflood/firefox-scripts#57]
![cannot_edit.gif](https://i.loli.net/2020/10/26/4pXtmsPvhGMkEU7.gif)

**Comment by xiaoxiaoflood** [comment]
Can't reproduce, working fine here, Fx83.

Maybe related to filename written in Chinese (?)? Could you please paste the name of the style?

**Comment by benzBrake** [comment]
The filename is `新建标签样式`.
I have tried to change filename to english, but it not worked.
I'm usting firefox 82 64bit with [portable_bin](https://sourceforge.net/projects/libportable/files/) patch.
Then I tryed to change Firefox version to firefox 82 portableapps version, firefox 82 official and firefox 83b4 official, all reproduce the problem.
* firefox 82 portableapps version
![ff82_portable_cannot_edit_english_filename.gif](https://i.loli.net/2020/10/26/j7sr1iGNpYlq9Pv.gif)
* firefox 82 official version
![ff82_cannot_edit_english_filename.gif](https://i.loli.net/2020/10/26/FtyDn1dgURLkwro.gif)
* firefox 83b4 official version
![ff83_cannot_edit_english_filename.gif](https://i.loli.net/2020/10/26/oCY4VQeEKLqZDBh.gif)

**Comment by xiaoxiaoflood** [comment]
Can't reproduce.
![](https://i.imgur.com/fW5O4SX.gif)

**Comment by benzBrake** [comment]
I fount this error message in browser toolbox
```
Uncaught 
Exception { name: "NS_ERROR_ILLEGAL_VALUE", message: "newChannel requires the 'securityFlags' property on the options object unless loading from system principal.", result: 2147942487, filename: "resource://gre/modules/NetUtil.jsm", lineNumber: 144, columnNumber: 0, data: null, stack: "NetUtil_asyncFetch@resource://gre/modules/NetUtil.jsm:144:22\ninit@chrome://userchromejs/content/styloaix/edit.js:53:13\nEventListener.handleEvent*@chrome://userchromejs/content/styloaix/edit.js:427:8\n", location: XPCWrappedNative_NoHelper }
NetUtil.jsm:144
```

**Comment by xiaoxiaoflood** [comment]
Probably your files are not updated. Please, be sure you have the latest version before creating an issue.

This was introduced in Fx 80 and fixed 3 months ago.

de708c7

**Comment by xiaoxiaoflood** [comment]
My mistake, sorry, I had forgotten to update styloaix.zip.
