### ISSUE TITLE
Partially disable multifoxContainer functionality

### ISSUE THREAD

**Issue by a-hwang** [xiaoxiaoflood/firefox-scripts#60]
How can I modify the script so that the when I open a new tab, it does not inherit the container of the current tab? I would prefer to keep the menu button when clicking on the icon. Thanks!

**Comment by xiaoxiaoflood** [comment]
Remove these two lines:
https://github.com/xiaoxiaoflood/firefox-scripts/blob/master/chrome/multifoxContainer.uc.js#L28-L29

```
      } else if (!options.relatedToCurrent && !options.userContextId && this.selectedTab.userContextId != UC.privateTab?.container.userContextId) {
        options.userContextId = this.selectedTab.userContextId;
```

**Comment by a-hwang** [comment]
> 
> 
> Remove these two lines:
> https://github.com/xiaoxiaoflood/firefox-scripts/blob/master/chrome/multifoxContainer.uc.js#L28-L29
> 
> ```
>       } else if (!options.relatedToCurrent && !options.userContextId && this.selectedTab.userContextId != UC.privateTab?.container.userContextId) {
>         options.userContextId = this.selectedTab.userContextId;
> ```

This worked, thanks!
