### ISSUE TITLE
statusbar script interacts with lower-right corner window resize on XFCE/Linux

### ISSUE THREAD

**Issue by Lalarian** [xiaoxiaoflood/firefox-scripts#63]
Hello again!

As you now know, I am using Waterfox on Linux.
Precisely it's Waterfox G3.0.2 based on Gecko 78.6.0.
The OS is Manjaro Linux, with XFCE desktop.

As the scripts now are generally running, there's one problem left, that's probably related to the desktop (window manager):

With the Statusbar script installed (which is working great!), the bottom right corner for resizing the Browser's window changes it behaviour, to actually move the upper left corner of the browser's window, when you drag it. The lower right corner just twitches around and always resets to it's former position while dragging.

I can make a video if required. Installing and configuring a screen grabber and such it would take me some time of course.

Thank you in advance! :+1:

**Comment by Lalarian** [comment]
I found a solution/workaround:
I removed the resize element from the script, by deleting the lines:
```
    let resizerContainer = _uc.createElement(document, 'toolbaritem', {id: 'resizer-container'});
    let resizer = _uc.createElement(document, 'resizer');
    resizerContainer.appendChild(resizer);
    win.statusbar.node.appendChild(resizerContainer);

```
Maybe this should be the default for Linux, as it looked wrong and didn't work right anways.

**Comment by Lalarian** [comment]
I found a solution/workaround:
I removed the resize element from the script, by deleting the lines:
```
    let resizerContainer = _uc.createElement(document, 'toolbaritem', {id: 'resizer-container'});
    let resizer = _uc.createElement(document, 'resizer');
    resizerContainer.appendChild(resizer);
    win.statusbar.node.appendChild(resizerContainer);

```
Maybe this should be the default for Linux, as it looked wrong and didn't work right anways.

![Bildschirmfoto_2020-12-28_10-50-47](https://user-images.githubusercontent.com/5146616/103205941-fc7ce700-48fa-11eb-8268-666a0439c082.png)

**Comment by xiaoxiaoflood** [comment]
I'll keep this open until I can test on Linux.

Pale Moon also has statusbar with resizer at lower right, maybe I should try it on Linux to se how it works.

**Comment by Lalarian** [comment]
Oh, right xD
It should be more like Win 2K, but you can't always get what you want..
It's the Chicago95 "Mod" https://github.com/grassmunk/Chicago95 with a Win2K skin.

**Comment by 1031982** [comment]
I know this is an old thread, but thank you Lalarian for your workaround. This was needed on my systems as well.
Irony is that I'm running Windows 10. I'm guessing it might be a conflict with one of my other customizations.

**Comment by xiaoxiaoflood** [comment]
I'm also using Linux now and already removed the buggy `resizer` from Status Bar.
