### ISSUE TITLE
Open in Unloaded Tab broken in FF 84

### ISSUE THREAD

**Issue by metronidazole** [xiaoxiaoflood/firefox-scripts#65]
No context link is added to open a link in an unloaded tabs in FF 84.

**Comment by xiaoxiaoflood** [comment]
Can't reproduce. I don't touch the code of this script since May 2019 and it still works for me on Fx 85.

![image](https://user-images.githubusercontent.com/25161346/105781238-fb1df900-5f50-11eb-8ebb-c29208445be9.png)

**Comment by metronidazole** [comment]
Strange. I toggled the script using the rebuild_userChrome.uc.js script and that seemed to fix the problem.
