### ISSUE TITLE
Rehost Image login bug

### ISSUE THREAD

**Issue by Sneakpeakcss** [xiaoxiaoflood/firefox-scripts#66]
Hello @xiaoxiaoflood , i'm not exactly sure if this is intended behavior but looks more like a bug.
After requesting PIN to imgur and signing in for the first time the extension recognizes the account and it creates an entry in firefox password manager with this data:

> Web Site Address: chrome://rehostimage
> Username: {myimguraccoutname}
> Password: a string of "random" letter/numbers.

**Imgur account settings says that the "Rehost Image" has access to the account.**

And now the bug:

_Rehost Image doesn't stay logged in/doesn't automatically upload to the previously added imgur account._

After signing in with PIN then closing the extension options window and opening it again, it doesn't recognize the account and asks for PIN once again.
Trying to login with another PIN puts it into infinite loading with an error in console log:
`NS_ERROR_FAILURE: This login already exists. 2 LoginHelper.jsm:1312`
Removing the entry from password manager allows it to login and recognize the account, but again only if the options menu isn't closed.

Extension technically uploads images to my account, but only if i manually login(and stay logged in) on imgur.com.
It doesn't matter if the entry in password manager exists or if it's registered as an app in imgur settings:

- If i upload an image with APP access and the Password Manager entry while manually logged in to imgur.com:
**_it uploads it to my account._**
- If i upload an image **without**  APP access and the Password Manager entry while manually logged in to imgur.com:
**_it once again uploads to my account._**
- If i logout from imgur.com it uploads as an anonymous user in both cases where APP access and PM entry exists or not.
- I also checked what would happen if i didn't close the option window after login(with PIN) and try to upload an image while logged out on imgur.com, and it turns out that even then it uploads as an anonymous user.

Initially i thought it was because i'm using Waterfox Current, but i've tested it on Firefox ESR/Firefox Current and Firefox Developer Edition and the problem stays the same.

**Comment by xiaoxiaoflood** [comment]
Thanks for your report!

This should be fixed now, just update Rehost Image.
