### ISSUE TITLE
The UC script sets the directory

### ISSUE THREAD

**Issue by blackdarks** [xiaoxiaoflood/firefox-scripts#67]
Hello! I’d like to ask, using the rebuild_userChrome.uc.js, how do I transfer the scripts from the Chrome folder to another folder under chrome? Because I don’t think it looks good with all the scripts in the Chrome folder, thanks.

**Comment by xiaoxiaoflood** [comment]
Done. Update your [userChrome.jsm](https://github.com/xiaoxiaoflood/firefox-scripts/blob/master/chrome/utils/userChrome.jsm) and change the line below as you wish
https://github.com/xiaoxiaoflood/firefox-scripts/blob/bf49a208e1363d376fef2d2e11f624fb8aaeed47/chrome/utils/userChrome.jsm#L8

For example, if you want to move `.uc.js` files from `chrome` to `chrome/js`:
`let scriptsDir = 'js'; `

**Comment by blackdarks** [comment]
thanks

**Comment by blackdarks** [comment]
More questions, what if it's adding several side-by-side subdirectories? e.g. Chrome/JS ,Chrome/TAB, Chrome/sub

**Comment by xiaoxiaoflood** [comment]
See #6.

**Comment by Marvinoo** [comment]
I wonder why this method is not compatible with `userChrome.jsm` that's inside `utils_scripts_only.zip`?
I want to use the _**utils_scripts_only**_ variant and along with that, I also want to change the scrips path but in `utils_scripts_only.zip`> `utils/userChrome.jsm` > `Line 8` the code :  `let scriptsDir = '';` doesn't exist! Please check that

**Comment by xiaoxiaoflood** [comment]
[userChromeJS.jsm](https://github.com/xiaoxiaoflood/firefox-scripts/blob/master/chrome/utils/userChrome.jsm) is the same file packed in `utils.zip` and in `utils_scripts_only.zip`.

Everything here is permanently subject to change (updates), so you shouldn't stick to line number. It was line 8 in February.

https://github.com/xiaoxiaoflood/firefox-scripts/blob/b675c520960c44a1bf5697f8a7df5e81502fc712/chrome/utils/userChrome.jsm#L22

**Comment by Marvinoo** [comment]
Okay thanks it's done.

**Comment by Wacky-Wombat** [comment]
> [userChromeJS.jsm](https://github.com/xiaoxiaoflood/firefox-scripts/blob/master/chrome/utils/userChrome.jsm) is the same file packed in `utils.zip` and in `utils_scripts_only.zip`.
> 
> Everything here is permanently subject to change (updates), so you shouldn't stick to line number. It was line 8 in February.
> 
> https://github.com/xiaoxiaoflood/firefox-scripts/blob/b675c520960c44a1bf5697f8a7df5e81502fc712/chrome/utils/userChrome.jsm#L22

Is this still supposed to work? 
Because for me, it doesn't. :(

**Comment by Teko101** [comment]
> > https://github.com/xiaoxiaoflood/firefox-scripts/blob/b675c520960c44a1bf5697f8a7df5e81502fc712/chrome/utils/userChrome.jsm#L22
> 
> Is this still supposed to work? Because for me, it doesn't. :(

Works for me. I think you should "Clear startup cache" and restart.

**Comment by Judefy** [comment]
> 
Can I use scriptsDir: 'file///xxx'  to put it on another disk?

**Comment by Judefy** [comment]
> [userChromeJS.jsm](https://github.com/xiaoxiaoflood/firefox-scripts/blob/master/chrome/utils/userChrome.jsm) is the same file packed in `utils.zip` and in `utils_scripts_only.zip`.
> 
> Everything here is permanently subject to change (updates), so you shouldn't stick to line number. It was line 8 in February.
> 
> https://github.com/xiaoxiaoflood/firefox-scripts/blob/b675c520960c44a1bf5697f8a7df5e81502fc712/chrome/utils/userChrome.jsm#L22

Can I use scriptsDir: 'file///xxx' to put it on another disk?
