### ISSUE TITLE
Script not working

### ISSUE THREAD

**Issue by kirk781** [xiaoxiaoflood/firefox-scripts#68]
I followed all the instructions listed in the article, yet I the script[MinimizeMaximize one to be precise] isn't working. Could it be due to the fact that I have a userchrome.css file to load as well? I am currently on latest Firefox for Windows and unzipped the files[fx ones] in the top level installation folder and then did as listed in the chrome folder.

**Comment by xiaoxiaoflood** [comment]
**MinMaxClose Button** is a very simple script, it works and what it does is create a button on your Firefox toolbar. If you're expecting anything beyond that, like hiding default window buttons, it doesn't do that. If the button wasn't created, then you must have done something wrong . It works if instructions are followed strictly.
