### ISSUE TITLE
Is it possible to disable the auto loading of dropped content of url bar (megabar).

### ISSUE THREAD

**Issue by mzso** [xiaoxiaoflood/firefox-scripts#69]
Hi!

Probably my biggest annoyance on current firefox versions of the nonsensical behavior of dropped text/url being automatically loaded. It was done supposedly for "security reasons", even though this way it will load malicious websites immediately if you happen to drop the wrong thing. (eg: not the whole url).
I've been looking all around to defeat this feature but to no success.

I see that "I'm not going to write a new script that I don't intend to use.". But maybe this is not just annoying to me.

PS:
There used to be a better alternative to dropping text, Simplify Awesome Bar ( caa:addon/simplify-awesome-bar ), that could send selected text to the urlbar. But now, even though it's still possible to install with the modifications from here, it's broken. At best it only succeeds at giving focus to the urlbar, and even that only when it is freshly enabled.

**Comment by xiaoxiaoflood** [comment]
Sorry, but I don't plan to work on this.
