### ISSUE TITLE
My Firefox Developer Edition 87.0b5 is not loading bootstrap addons right

### ISSUE THREAD

**Issue by 117649** [xiaoxiaoflood/firefox-scripts#70]
I'm trying use multiple bootstrap addons and found that browser startup have a big chance been interrupt and hangs especially when having more than one addons enabled and restore a session. (most of the UI are loaded but not the tabs of restored session, tool bar button's menu, booksmark bar items)
I'm using script loader for addons.
And Tab Groups just not been loaded while browser start.
Are you seeing any of this?

Addons:
[roomybookmarksredux](https://github.com/p1usminus/roomybookmarksredux/commit/70bd876dd2065d529e669b9a71da3e87f91e3205)
[TMP](https://github.com/onemen/TabMixPlus/tree/rewrite/main)
[Tab-Groups](https://github.com/117649/Tab-Groups)

**Comment by xiaoxiaoflood** [comment]
I use all my 9 addons from this repo plus BackTrack Tab History, the session I restore daily has more than 200 tabs and I have no issues. DevEd 87.0b5.

So I guess the issue is in one of those addons you use, not in bootstrap loader.

**Comment by 117649** [comment]
https://github.com/onemen/TabMixPlus/issues/35#issuecomment-791212742
Fixed here.

But here I also encourage you to try out this new TMP and see if there is anything you like or find any issue.

**Comment by xiaoxiaoflood** [comment]
The few things from TMP I like, I get from other ways. But thank you and great work, it had a million users and it will be great to have it back.

Your addon that I'm really interested in is Tab Groups, I had it. But WebExtensions now supports tab groups too, so I don't know if there are any advantage in using the legacy version. I'm currently using Tiled Tab Groups. What prevents my from giving legacy Tab Groups a try is the lack of compatibility with Tree Style Tab (I need submenu "Move tab to group" when right-clicking a tab in TST).

**Comment by 117649** [comment]
I just like the full window group display UI so I bring it back, one thing I don't think there is a way web-ext can achieve same.
AS for the TSB compatibility if it using original contextmenu of the tab there is a big chance that submenu is already there. If not I don't think there is much can be done on Tab Groups side.
