### ISSUE TITLE
Restart Firefox button on Panel Menu is broken

### ISSUE THREAD

**Issue by AlexVallat** [xiaoxiaoflood/firefox-scripts#71]
a1d8cf42e2a906a6c69acd65844dc44fbf59e20f fixed removal of restart, but did so only for the tools menu, not the panel menu. Panel menu still seems to be calling BrowserUtils.restartApplication()

**Comment by xiaoxiaoflood** [comment]
Fixed, thanks.

**Comment by xiaoxiaoflood** [comment]
@AlexVallat, BackTrack is still using `BrowserUtils.restartApplication()`.

**Comment by AlexVallat** [comment]
Yes, good catch, thanks. I've created #75 with a fix.
