### ISSUE TITLE
savefileto breaks context menu (Nightly, 88.0a1)

### ISSUE THREAD

**Issue by askii2** [xiaoxiaoflood/firefox-scripts#73]
savefileto breaks the content context menu on Firefox Nightly since build 88.0a1 / 20210304092248. 

![Screen Shot 2021-03-17 at 06 18 10](https://user-images.githubusercontent.com/15678782/111285524-fc4dd700-861f-11eb-9adc-906c88e94eae.png) 

The extension items are not hidden according to the preferences and their sub-menus don't show when hovered. Many native items don't work as well when clicked or hovered (e.g. all "Open Link" entries). The preferences dialog and the Save File dialog still work normally.

I believe this is the relevant change: https://hg.mozilla.org/mozilla-central/rev/873822e544614bd755622f8857c8c8dd2b08c5a4, but i'm not sure.

The browser console throws these errors:

```
Uncaught TypeError: can't access property "children", aPopup is null
    showHideSeparators chrome://browser/content/nsContextMenu.js:1061
    showHideSeparators chrome://browser/content/nsContextMenu.js:1082
    initItems chrome://browser/content/nsContextMenu.js:339
    nsContextMenu chrome://browser/content/nsContextMenu.js:171
    onpopupshowing chrome://browser/content/browser.xhtml:1
    openContextMenu chrome://browser/content/nsContextMenu.js:94
    receiveMessage resource:///actors/ContextMenuParent.jsm:23
    JSActor query*handleEvent resource:///actors/ContextMenuChild.jsm:727
nsContextMenu.js:1061:26

Uncaught TypeError: can't access property "hiding", gContextMenu is null
    onpopuphiding chrome://browser/content/browser.xhtml:1
browser.xhtml:1:97
```

**Comment by xiaoxiaoflood** [comment]
Thanks for the detailed report.

This should be fixed now.
