### ISSUE TITLE
Cant find proper location to place config.js and config-prefs.js on Linux

### ISSUE THREAD

**Issue by tortious** [xiaoxiaoflood/firefox-scripts#8]
I am not sure what location to put these files in on Manjaro Linux (KDE Plasma). 

Everything seems to be located at /home/myusername/.mozilla/firefox/myprofile/

Your instructions state to place the config.js and config-prefs.js in the firefox installation folder (with the latter being placed within \defaults\prefs). However, aside from the path mentioned above, I am having trouble finding anything else that looks like it could be my firefox installation folder. 

I also tried looking for channel-prefs.js to get a frame of reference as to my installation folder location, but could not find that either. 

 Please help. Thank you!

**Comment by xiaoxiaoflood** [comment]
http://kb.mozillazine.org/Installation_directory#Linux
> Examples of default installation directories (64-bit Linux):
> Firefox | /usr/lib/firefox-<version>

https://developer.mozilla.org/en-US/docs/Mozilla/Firefox/Enterprise_deployment_before_60#Configuration
> This file [config.js] should be put inside:
>     on Linux:
>         Formerly:
>             defaults/pref
>             (Still working in Firefox 60.0a1)
>         Presently:
>             browser/defaults/preferences

But I don't use Linux (yet), so I'm not sure.

**Comment by mozo78** [comment]
It's working great on Linux, thank you :)
https://i.imgur.com/vhogQMU.png

**Comment by Lalarian** [comment]
Hello! Could you please explain this more detailed?
'config.js' belongs into 'waterfox-g3/browser/defaults/preferences/' now. But where does 'config-prefs.js' go now?

**Comment by xiaoxiaoflood** [comment]
I don't use Linux, but I think I need to edit my comment above.

Here on Windows, config.js must be placed along with Firefox executable, and config-prefs must be placed a little deeper, into \defaults\prefs. On Linux, it seems that the folder is named "preferences" instead of "prefs" and that "defaults" folder it's inside "browser" folder.

The thing is that in my previous comment I said that config.js must be placed in preferences folder, but it should be config-prefs.js.

So something like:
/usr/lib/firefox/config.js
/usr/lib/firefox/browser/defaults/preferences/config-prefs.js

Try this and tell me if it works, so I can edit my previous comment.

**Comment by Lalarian** [comment]
Yes, this seems to work (besides the UI looking bugged in details, the pathes seem to be working).
So adapted to my setup (with Waterfox and installation in /opt) it's looking like this:

****/opt/waterfox-g3/browser/defaults/preferences/config-prefs.js**
/opt/waterfox-g3/config.js**

Thank you! :+1: 

Btw: During this I found that the 'old' path still exists, which is adding some confusion:
'/opt/waterfox-g3/defaults/pref/channel-prefs.js'
Can I assume this is outdated and should be deleted, from my interpretation of

> Formerly:
> defaults/pref
> (Still working in Firefox 60.0a1)
> Presently:
> browser/defaults/preferences
?

**Comment by xiaoxiaoflood** [comment]
Thank you, comment updated.

About unpolished UI, unfortunately it's expected because I don't test on Linux and there are minor CSS differences here and there. Maybe someone could write fixes and submit them for me.

**Comment by Lalarian** [comment]
Where would I have to search for the reason the button is not there?

**Comment by xiaoxiaoflood** [comment]
> rebuild_userChrome.js

It should be `rebuild_userChrome.uc.js`.

**Comment by Lalarian** [comment]
Oh, sorry - it actually is. That was just a type of mine.
I just remembered that I could find a way for clearing the startup cache in the beginning.
Because there's neither a button for doing so in about:supportt nor is there a directory named 'startupCache' in my profile folder..

Maybe this is the reason.

**Comment by xiaoxiaoflood** [comment]
If status-bar.uc.js is working for you, the issue here is not about startupCache. 

Keep in mind that I use Firefox Developer Edition, currently in version 85. Things may or may not work on other versions (apparently you're using Waterfox based on Fx 78), I don't officially support any other version than current DevEv.

Rebuild's button should be automatically placed next to urlbar. There's also the item in hamburger menu:
![](https://i.imgur.com/XGUG20r.png)

And it's possible to replace the icon by item in Tools menu:
![](https://i.imgur.com/fTCvMWW.png)

**Comment by Lalarian** [comment]
Wow, both items don't exist in my browser. Neither The Manager's entry in the Tools menu, nor 'UserScripts' in the hamburger menu.
About menu says 'based on Gecko 78.6.0'. So probably my browser is too old.

I just naively I entered the rebuild-button-script into Tampermonkey and executed it through the context menu. Result was:
`ERROR: Execution of script 'userChromeJS Manager' failed! UC is not defined`
But probably this is just a matter of scope, I assume..

**Comment by xiaoxiaoflood** [comment]
userChromeJS scripts (.uc.js) are totally different than normal UserScripts (.user.js).

Well, rebuild is not running for you. The reason, unfortunately, only you can debug. Just make sure rebuild_userChrome.uc.js is in chrome folder, in the same location as status-bar.uc.js and any other .uc.js. And you need to restart Firefox to apply.

**Comment by Lalarian** [comment]
OK, then thank you very much! :+1: 
Finally my browser is working again - I can even move AddOn induced items into the new status bar, that's what I needed. Probably the rest is going to work once Waterfox (or even Firefox stable) reaches the required version.

**Comment by xiaoxiaoflood** [comment]
I just tried on Fx 78 and it's working. I don't know if Waterfox has something exclusive that may break it, but I don't think so. If status-bar is running, userChromeJS is running. So just save [rebuild](https://raw.githubusercontent.com/xiaoxiaoflood/firefox-scripts/master/chrome/rebuild_userChrome.uc.js) in the same folder you put satus-bar.uc.js and restart Firefox (Waterfox).

**Comment by xiaoxiaoflood** [comment]
> where could I see debugging information about userchrome scripts?

Open about:config, set `devtools.chrome.enabled` to `true`. Open Browser Console (at least on Widows you can do it with Ctrl+Shift+J), paste `_uc.scripts` and press Enter, then you'll see all installed userChromeJS scripts.

**Comment by Lalarian** [comment]
Good to hear that it should be working. Gonna try to find some debugging info now!

**Comment by Lalarian** [comment]
I found an error that comes with the rebuild script:
`07:33:52.671 CustomizableUI: Custom widget with id userChromebtnMenu does not return a valid node CustomizableUI.jsm:1692`

**Comment by xiaoxiaoflood** [comment]
Well, rebuild is on the list. The next step would be searching for errors caused by "userChrome" in Browser Console just after launching Firefox...

**Comment by Lalarian** [comment]
I found an error that comes with the rebuild script:
`07:33:52.671 CustomizableUI: Custom widget with id userChromebtnMenu does not return a valid node CustomizableUI.jsm:1692`

Sorry for posting twice - I posted without reloading first :)

**Comment by xiaoxiaoflood** [comment]
This must be Waterfox specific, because there are no errors in Firefox. Sorry, but I don't plan to support other browsers.

If you run this on Browser Console, it returns true or false?
`[...document.getElementById('menu_ToolsPopup').children].includes(document.getElementById('menu_preferences'))`

**Comment by Lalarian** [comment]
Somehow the console windows got messed up :(
The input line moved from the bottom to the left and I cannot see any response to the comm
![Bildschirmfoto_2020-12-28_07-53-09](https://user-images.githubusercontent.com/5146616/103195269-38f01900-48e2-11eb-9526-d62f9a99791e.png)
ands anymore.

**Comment by Lalarian** [comment]
Hm. no idea, but somehow I just fixed it after 10 minutes of fiddling :)

Your requests results in false :(
```

07:57:01.024 [...document.getElementById('menu_ToolsPopup').children].includes(document.getElementById('menu_preferences'))
07:57:01.067 false
```

**Comment by xiaoxiaoflood** [comment]
I think I got it. It's not Waterfox related, but Linux related. On Linux, Preferences is under Edit menu, not under Tools (and on Windows, is "Options" instead of "Preferences").

I'll try something...

**Comment by Lalarian** [comment]
Oh, it would be super if that helped :)
I could exactly note this issue, as I also have the German translation installed :)

**Comment by xiaoxiaoflood** [comment]
In rebuild code, try replacing
`aDocument.getElementById('menu_ToolsPopup')`
by
`aDocument.getElementById('menu_preferences').parentElement`

Save then restart Firefox. It should work.

I'll soon upload the updated script with something like this.

**Comment by Lalarian** [comment]
It's working! :+1:

**Comment by xiaoxiaoflood** [comment]
Script updated, thank you.

**Comment by guillaumedavidphd** [comment]
Hello there!
I'm having a hard time finding the correct location. I'm running Ubuntu 21.10, which uses the Snap version of Firefox by default. Is it at all possible to use `firefox-scripts` with the Snap version?
Any help is appreciated!

**Comment by mozo78** [comment]
Any reason using snap FF? Uninstall the snap version and install the regular version:
`sudo apt install firefox`

**Comment by guillaumedavidphd** [comment]
@mozo78 No reason in particular, it's just the default version that ships with Ubuntu these days. I'm wondering if it's possible to use `firefox-scripts` with it. I do know that I can choose to uninstall the default snap version and install the apt version as an alternative. But it's not really what I'm asking here.

**Comment by mozo78** [comment]
I see :) Let's hope [xiaoxiaoflood](https://github.com/xiaoxiaoflood) will know.

**Comment by xiaoxiaoflood** [comment]
I don't know, I don't use Linux (yet, maybe).

**Comment by mozo78** [comment]
Great mistake :)

**Comment by BICH0** [comment]
Hi, i have followed all the steps in the installation and i cant  manage to make it work, i tried changing the ownership and permissions of the files with no luck, these are the paths that i am using:
/usr/lib/firefox/config.js
/usr/lib/firefox/browser/defaults/preferences/config-prefs.js (i also tried inside /usr/lib/defaults/pref/)
Im running firefox-99.0.1-1

**Comment by AdamPS** [comment]
> Any reason using snap FF? Uninstall the snap version and install the regular version: `sudo apt install firefox`

With Ubuntu 22.04 there is no longer a firefox apt package. So far I can't seem to get it to work with snap. Here's what I've found so far:

- [Issue on snapcraft](https://forum.snapcraft.io/t/firefox-snap-no-longer-reads-usr-lib-firefox-for-customization/29713)
- [Mozilla bug report](https://bugzilla.mozilla.org/show_bug.cgi?id=1785278)

**Comment by Massimo-B** [comment]
How can I get this installed on FF 102.3.0 (ESR) on Linux? I can't find any config.js or config-prefs.js on my Firefox installation.

**Comment by EzPzDev** [comment]
> Hi, i have followed all the steps in the installation and i cant manage to make it work, i tried changing the ownership and permissions of the files with no luck, these are the paths that i am using: /usr/lib/firefox/config.js /usr/lib/firefox/browser/defaults/preferences/config-prefs.js (i also tried inside /usr/lib/defaults/pref/) Im running firefox-99.0.1-1 Edit: i found a workaround for this issue, at least in my case the chrome.manifest needed to be inside ~/.mozilla/firefox/randomnumber.default-release/chrome/utils/ So the references inside the manifest needed to be changed to make sense: `content userchromejs ../` `resource userchromejs ../..` So everything solved ;)

This also worked for me on OpenSUSE Tumbleweed with FF104. The path for fx-folder.zip was:
 `/usr/lib64/firefox/config.js`
`/usr/lib64/firefox/browser/defaults/preferences/config-prefs.js`
There's also a `/usr/lib64/firefox/defaults/pref/` folder but I didn't use it.

The trick, thanks to @BICH0, was to move chrome.manifest into a new (at least for me) folder called `utils` in `~/.mozilla/firefox/$firefox.profile/chrome/` then updating the references in the manifest. Content should point to your chrome folder and resource should point to your profile folder.

**Comment by benyaminl** [comment]
My question, when we update using package manager, @EzPzDev, does we need to backup all first so the data doesn't get lost or let the package manager done it, and the addons/JS still there? Thanks

**Comment by EzPzDev** [comment]
I'm probably not the best person to ask, and I recommend having at least a backup folder (preferably not on your main storage) to keep various files you've added or changed on your system. 

That being said; as long as Firefox doesn't change it's file structure or anything everything should still be there when you update using your package manager. Your `chrome` folder with your addons/JS should definitely persist between Firefox updates.

**Comment by mozo78** [comment]
You don't need to backup anything.

**Comment by KarlG1965** [comment]
Hi, can anyone advise me how to do this when firefox is installed in /opt/firefox?

I don't use apt, snap or flatpak - I just download the zip file from mozilla's website and extract it to the /opt folder-

**Comment by tomchiverton** [comment]
The above should be sufficient. What happens when you try?

**Comment by KarlG1965** [comment]
I don't have all the folders mentioned - for example, I dont' have an /etc/firefox directory so I can't try the above

**Comment by tomchiverton** [comment]
Create the folders if they don't exist. Sorry if this wasn't clear.

Any further issues should probably be on a new issue, not this closed one. 
-- 
†øღ

**Comment by KarlG1965** [comment]
Apologies, I didn't notice that this issue was closed. I'll create a new issue

**Comment by eyalroz** [comment]
This thread still doesn't contain valid instructions on how to install these files on Firefox on Linux. The relevant folders often don't exist - and there's no reason to believe firefox will search those folders for anything. Give a Firefox installation under `/some/path`, what folders should be created? Should these files replace existing ones? What guarantees they will be read, when copied somewhere?

**Comment by tomchiverton** [comment]
The instructions won't be in this thread, it's closed. The docs are clear, and WFM (Ubuntu 25.04, Snap and non-Snap) : https://onemen.github.io/tabmixplus-docs/other/installation/
I believe them to be clear about creating the paths if missing.

The installation locations are supported-by-Mozilla extension methods, they will be searched for and read.
