### ISSUE TITLE
Resize Status Bar

### ISSUE THREAD

**Issue by mozo78** [xiaoxiaoflood/firefox-scripts#80]
Hello,
It's not an issue but a question. Do someone know how to resize the statusbr for it's a bit taller to my taste? I searched through the scripts but didn't find anything useful.
Thank you in advance :)

**Comment by xiaoxiaoflood** [comment]
You can do it with CSS (using StyloaiX or userChrome.css). Example:

```css
#status-bar {
  height: 30px;
}
```

Or simply edit status-bar.uc.js adding the line `height: 30px;` (changing the value as you wish) right here:
https://github.com/xiaoxiaoflood/firefox-scripts/blob/e82e9fb20300605a0d43213bf9654a752746a802/chrome/status-bar.uc.js#L120-L123
`#status-bar { }

**Comment by mozo78** [comment]
Working great, thank you very much!
