### ISSUE TITLE
Is restoring the rss/etc feed viewing and subscribing capability possible?

### ISSUE THREAD

**Issue by mzso** [xiaoxiaoflood/firefox-scripts#85]
Kind of sucks that I can't  do it anymore.

I didn't use the livemarks, but why on earth did they remove the subscribe and view feature as well? It worked fine with external services

**Comment by zakius** [comment]
There are extensions for preview, some of which provide subscription support for common services, but honestly I believe using detection mechanism of your reader/service is the most reliable (if it has any of course) as the most basic one often isn't enough (like for YouTube, where it doesn't update the `head` section of markup when navigation *and* doesn't trigger history events so you have to use `MutationObserver` and build feed links from the address instead of relying on ones provided in `head`)

**Comment by xiaoxiaoflood** [comment]
It's probably possible, but I won't work on it because I don't use it, sorry. I recommend Inoreader.com, that's what I use.

**Comment by mzso** [comment]
[**@xiaoxiaoflood**](https://github.com/xiaoxiaoflood) commented on [2021. aug. 1. 07:55 CEST](https://github.com/xiaoxiaoflood/firefox-scripts/issues/85#issuecomment-890457103 "2021-08-01T05:55:29Z - Replied by Github Reply Comments"):
> It's probably possible, but I won't work on it because I don't use it, sorry. I recommend Inoreader.com, that's what I use.

I also use Inoreader. But without the feed discovery and subscription feature it's more troublesome.


[**@zakius**](https://github.com/zakius) commented on [2021. jún. 25. 09:14 CEST](https://github.com/xiaoxiaoflood/firefox-scripts/issues/85#issuecomment-868279673 "2021-06-25T07:14:15Z - Replied by Github Reply Comments"):
> There are extensions for preview, some of which provide subscription support for common services (like [https://addons.mozilla.org/en-US/firefox/addon/feed-preview/](https://addons.mozilla.org/en-US/firefox/addon/feed-preview/) if you want subscription or [https://addons.mozilla.org/en-US/firefox/addon/rsspreview/](https://addons.mozilla.org/en-US/firefox/addon/rsspreview/) if you prefer the classic preview layout), but honestly I believe using detection mechanism of your reader/service is the most reliable (if it has any of course) as the most basic one often isn't enough (like for YouTube, where it doesn't update the `head` section of markup when navigation _and_ doesn't trigger history events so you have to use `MutationObserver` and build feed links from the address instead of relying on ones provided in `head`)

I missed this reply. Thanks I"ll have a look at them. I actually used more services. Notably, besides inoreader Blogtrottr, which sent new items via e-mail, for an interval. It was useful for feeds that rarely got updated.

**Comment by peterwx** [comment]
@mzso `Feedbro` extension has detection, preview, subscribing (but no sync), filter (on both title and content) capabilities. One can add feeds from `Twitter`, `Reddit` and `Youtube` as well - (for the full list, view the store description). Full page content loading is possible but not consistent - results vary with each website.
I'll also mention that there are `userscripts` for `Feedly` and `Inoreader` that enable filtering capabilities and full page content loading.
Such features, which are part of paid plans in those web services can be had at no cost with the combination of scripts and extensions mentioned.

**Comment by mzso** [comment]
@peterwx
Thanks for the tip. I'll check it out.
