### ISSUE TITLE
Styloaix edit style not working due to document.popupNode removal

### ISSUE THREAD

**Issue by askii2** [xiaoxiaoflood/firefox-scripts#87]
Mozilla [replaced](https://hg.mozilla.org/mozilla-central/rev/a9166de3f917456eefb74d9d0792a0dde25997fe) and [removed](https://hg.mozilla.org/mozilla-central/rev/141b15981515d33aedb3c1edd8505956b2494730) `document.popupNode` in favor of `popup.triggerNode`.
So in styloaix.uc.js, we can replace `document.popupNode._style` with `this.parentNode.triggerNode._style`

**Comment by xiaoxiaoflood** [comment]
Done in https://github.com/xiaoxiaoflood/firefox-scripts/commit/cf0337bd51bf420418976952bcb07bfd20cefd47#diff-997fff57371cef015b7ee8fcd686ac3a1547d6ad30212e52a61851d53ffae337, thanks.
