### ISSUE TITLE
Unsigned addons cannot be loaded on Firefox stable

### ISSUE THREAD

**Issue by Altsinn** [xiaoxiaoflood/firefox-scripts#89]
Hello, 

After Firefox 90 release, it is no longer possible to load unsigned addons. I assume that this bug can be the culprit:

https://bugzilla.mozilla.org/show_bug.cgi?id=1712633

Can it be fixed somehow in your scripts? Thanks in advance!

**Comment by Altsinn** [comment]
I found out that above issue was caused by confict with Aris-t2 'CustomJSforFx scripts' that I also use.

**Comment by benyaminl** [comment]
@Altsinn so we can't install it then on stable?
