### ISSUE TITLE
can not open new links after installing ublock， bootstrap

### ISSUE THREAD

**Issue by GoogleBeEvil** [xiaoxiaoflood/firefox-scripts#9]
after installing ublock， bootstrap，restart the  browser,then cannt open any link which is never visited, there r  errors in console
源映射错误：TypeError: NetworkError when attempting to fetch resource.
源 URL：resource://activity-stream/data/content/activity-stream.bundle.js
源映射 URL：activity-stream.bundle.js.map

**Comment by xiaoxiaoflood** [comment]
I use uBO flawlessly. I think your problem isn't related to my code.
