### ISSUE TITLE
Need to turn xpinstall.whitelist.required off 

### ISSUE THREAD

**Issue by onemen** [xiaoxiaoflood/firefox-scripts#92]
We have this one record confirms that set xpinstall.whitelist.required=false helps 'file corrupt' error, when trying to install [Tab MIx Plus](https://github.com/onemen/TabMixPlus).
https://dm.reddit.com/r/FirefoxAddons/comments/pm53qx/github_onementabmixplus_at_v100pre1/hcjn36a/

Can you add setting xpinstall.whitelist.required to false to your scripts and bootstrapLoader ?

**Comment by xiaoxiaoflood** [comment]
Your Reddit link doesn't even mention `xpinstall.whitelist.required`.

I just tested again now and this pref is not needed, my instructions still works. Reinforcing:

Release/ESR/Beta: can't install experiments, so bootstrapLoader is not an option, the user must install userChromeJS.
DevEd/Nightly: the user can choose between the two options (I recommend and use userChromeJS).

For userChromeJS, just copy a couple of files to firefox.exe folder, copy the `user` folder to `profile\chrome` and restart Firefox. It's possible that startupCache isn't cleared on restart, so it's recommended to click `Clear startup cache...` in `about:support` before restarting.

For bootstrapLoader, first set the two prefs as instructed, install the bootstrapLoader.xpi, then restart Fx and just click the TMP's XPI link.

Tested with current release (Fx 92.0, userChromeJS) and Nightly (94.0a1 2021-09-16, bootstrapLoader.xpi and userChromeJS), fresh new installations (2) and fresh new profiles (3 in total).

**Comment by onemen** [comment]
Thank you.
In my readme.md user linked to your pages.
![install-s](https://user-images.githubusercontent.com/3650909/133745396-0e1826f8-ed36-4ca5-ad65-046638ec86ab.png)

...and look like many users are still confused or having problems.

maybe, if you are interesting, we can build a new site at Github pages or elsewhere,  with all the steps to install legacy extensions of Firefox.

I don't think that adding different instruction on each extension page is a good

**Comment by xiaoxiaoflood** [comment]
OK. Feel free to suggest any change.

I agree that it's possible to get better, but I don't think my current text and structure are that confusing.

Unless we provide an executable setup or similar (which could scary people), users need to do the things manually, messing with files and folders.

I don't see nothing hard to understand or to do in the instructions, but I'm open to suggestions. Starting from [here](https://github.com/xiaoxiaoflood/firefox-scripts/tree/master/extensions#readme), I guess it's kinda easy.

Honestly, the hardest and undocumented part is how to install the XPI, because I don't say nothing about it and clicking to Download doesn't trigger the install dialog. But you don't have this problem because the XPI link in Releases page *do* triggers the install dialog just like as in AMO.

**Comment by onemen** [comment]
My problem so far is that i don't know with what exactly user are strangles

**Comment by 117649** [comment]
I think some picture display the final result of content and structure of the folders that need manual operation could definitely help.

I do see people question things like "do I need **utils** at all?".

Anybody care to give shell scripts a try?

**Comment by 117649** [comment]
> 
> 
> My problem so far is that i don't know with what exactly user are strangles

That is really some of the hardest problem of the mankind.

For most case I doubt they just not clear startup cache properly.

**Comment by onemen** [comment]
> Anybody care to give shell scripts a try?

do you mean running script from the terminal ?

**Comment by 117649** [comment]
> 
> 
> > Anybody care to give shell scripts a try?
> 
> do you mean running script from the terminal ?

I think .bat is executable with double click on Windows?

**Comment by onemen** [comment]
I'v just successfully installed bootstrapLoader extensions on Firefox 92
set: extensions.experiments.enabled = true

and its work

maybe we can create helper extension installer.xpi that will automatically (after asking for user permission), 
  * check if user add the proper config file to Firefox installation folder, if not do it. 
  * add the proper script to current profile, if it is not exist already. 
  * clear cache and restart.
  * remove itself after notify the user about success or failure.

**Comment by 117649** [comment]
> 
> 
> I'v just successfully installed bootstrapLoader extensions on Firefox 92
> set: extensions.experiments.enabled = true
> 
> and its work
> 
> maybe we can create helper extension installer.xpi that will automatically (after asking for user permission),
> 
>     * check if user add the proper config file to Firefox installation folder, if not do it.
> 
>     * add the proper script to current profile, if it is not exist already.
> 
>     * clear cache and restart.
> 
>     * remove itself after notify the user about success or failure.

I don't know but that just sound a loop back lock.
If you can get bootstraploader work you don't need and should not install script...
And if something that can modify user's computer is in use why not just let it place **.xpi** in to user's profile folder directly?

**Comment by onemen** [comment]
@xiaoxiaoflood  recommendation is to use the script
we will only use the installer.xpi extension to automatically install the script.
since we get so many report about problems we need to address the issue somehow

**Comment by 117649** [comment]
> 
> 
> @xiaoxiaoflood recommendation is to use the script
> we will only use the installer.xpi extension to automatically install the script.
> since we get so many report about problems we need to address the issue somehow

I mean how could you install it if script is not in place?

**Comment by onemen** [comment]
i will need to check if it is possible to do it with the the experimental api

**Comment by xiaoxiaoflood** [comment]
> maybe we can create helper extension installer.xpi that will automatically (after asking for user permission),

By doing that, you're eliminating 99% of users, those who don't use DevEd nor Nightly. Only those two versions can installl experiments.

You said you installed bootstrapLoader (an Experiment) on Fx 92, but I guess you did it while your Fx 92 was already unlocked with `fx-folder.zip` files (like config.js), which defeats the main purpose of a helper extension.

You can't install any WebExts Experiment in release/beta/ESR by just toggling some `about:config` prefs.

**Comment by xiaoxiaoflood** [comment]
I may upload a video showing the installation steps. It's unfortunate how difficult people are to follow basic instructions. 🤦‍♂️

**Comment by xiaoxiaoflood** [comment]
Look at Firefox source, `extensions.experiments.enabled` has no effect in release/Beta/ESR:
https://searchfox.org/mozilla-central/rev/45e308665eb9fc52fd21e2d4b3b959f3cec13ef1/toolkit/mozapps/extensions/internal/AddonSettings.jsm#92-126

...unless you have already applied config.js in installation folder, because config.js *hacks* the Firefox lock:
https://github.com/xiaoxiaoflood/firefox-scripts/blob/bf9955004fb93e5032e7a4b15a6e26e8f01a2356/installation-folder/config.js#L10

**Comment by onemen** [comment]
@xiaoxiaoflood , you are right

If user know how to install ```fx-folder.zip``` files, they know how to install the scripts.

**Comment by xiaoxiaoflood** [comment]
Video added to read-me. This should help.
