### ISSUE TITLE
I've extensionOptionsMenu.uc.js installed correctly but it doesn't load anymore 

### ISSUE THREAD

**Issue by Marvinoo** [xiaoxiaoflood/firefox-scripts#95]
Hello, 
 Although this script is correctly placed into folder together with other working scripts, it's the only one that stopped showing it's button suddenly and I've no idea how to make it's button to show again. I tried 'Clear startup cache' multiple times but still no luck. Script is just there but refuses to show the toolbar button.

**Comment by 117649** [comment]
Are you using 93+? it breaks several scripts.

**Comment by Marvinoo** [comment]
> 
> 
> Are you using 93+? it breaks several scripts.

No, I'm still on 92
![firefox_fmpo5SwPvU](https://user-images.githubusercontent.com/45720537/133758812-d34c62f5-3cb6-4faf-9101-bc76fa0c0f54.png)
Also have these scripts and they work as expected except extensionOptionsMenu.uc.js
![9ZmLh2HdyX](https://user-images.githubusercontent.com/45720537/133759485-20ec51a7-302b-4ba8-b630-2eec1f6f5099.png)

**Comment by xiaoxiaoflood** [comment]
> Are you using 93+? it breaks several scripts.

I just updated to Fx 93 and everything seems to be working, including EOM. The only script broken in Fx 93 was rebuild_userChrome.uc.js, already updated. The legacy addons I use are also working without any changes.

**Comment by Marvinoo** [comment]
Solved

**Comment by Marvinoo** [comment]
@xiaoxiaoflood  Hey, is it possible to change the default path for `.uc.js` scripts? 
I want to move them from the main `chrome`folder and put them inside a sub folder in the `chrome` folder called 'JS'
So I modified the `chrome.manifest`file and changed the path from :

> content userchromejs ./

To 

> content userchromejs ./JS/

but the loader failed to get the scripts, what am I doing wrong?

**Comment by Marvinoo** [comment]
> 
> 
> @Marvinoo
> 
> Please read it here:
> #67
> 
> You shouldn't modify `chrome.manifest`.

It helped. Thanks a lot.
