### ISSUE TITLE
Firefox rejects TMP extension

### ISSUE THREAD

**Issue by VLM-TechEd** [xiaoxiaoflood/firefox-scripts#96]
Greetings, and thank you for sharing this fine work!

I am running regular (not dev) Firefox, version 92.0.

1. As instructed, I downloaded fx-folder.zip and extracted its contents to c:\Program Files\Mozilla Firefox.

2. I downloaded utils.zip for both scripts and extensions and extracted the files to %AppData%\Roaming\Mozilla\Firefox\Profiles\<profile.default-release>\chrome.The folder utils appears there with all its contents intact. 

I also downloaded the scripts rebuild_userChrome.uc.js and extensionOptionsMenu.uc.js into the chrome folder. 

3. I opened about:support, cleared the startup cache, and restarted Firefox. 

4. I dragged the new TabMixPlus extension onto the Extensions window. Firefox responded with "This add-on could not be installed because it appears to be corrupt." In addition, the button to manage extensions does not appear.

Obviously, I've done something incorrectly, but I don't see what the error may be. Can anyone help spot my error?

Thanks!

**Comment by VLM-TechEd** [comment]
One more detail: I am running both Pale Moon and Firefox. Windows thinks that by default, .xpi files should be opened by Pale Moon. But I dragged the TMP .xpi file directly onto the Firefox extensions window/tab multiple times, so I don't believe this is a problem. Still, I share it, "just in case".

**Comment by 117649** [comment]
> 
> 
> One more detail: I am running both Pale Moon and Firefox. Windows thinks that by default, .xpi files should be opened by Pale Moon. But I dragged the TMP .xpi file directly onto the Firefox extensions window/tab multiple times, so I don't believe this is a problem. Still, I share it, "just in case".

Which version of .xpi you drag into Firefox?

**Comment by xiaoxiaoflood** [comment]
Just today I uploaded a video showing the process of installing userChromeJS and legacy extensions in regular Fx 92, you can find the link in the main read-me. In the video I used `rebuild_userChrome.uc.js` to test userChromeJS and DownThemAll! to test legacy extensions, but `extensionOptionsMenu.uc.js` and TMP also works*.

*: I can assure that TMP installs just fine, but other than that it's responsibility of its dev.

I didn't see any issue in what you said you did, but if it's not working I guess you made a mistake at some point, but only you can inspect that, since what you said seems correct and that the provided instructions worked for many people.

**Comment by VLM-TechEd** [comment]
Thank you for responding so quickly. I appreciate it.

More information: I already had a chrome folder, in which I already had:

userChrome.css (contains some code related to multirow tabs)
userContent.css (empty at the moment)

as well as the three new items:

utils (folder)
extensionOptionsMenu.uc.js.html
rebuild_userChrome.uc.js.txt 

In Program Files\Mozilla Firefox, I now have fx-folder, which contains defaults (folder) and config.js .

Do these elements seem correct and complete to you?

**Comment by xiaoxiaoflood** [comment]
> extensionOptionsMenu.uc.js.html

That's the error. You probably downloaded the display page of the script, not the script itself. You probably downloaded this link:
https://github.com/xiaoxiaoflood/firefox-scripts/blob/master/chrome/extensionOptionsMenu.uc.js

But should instead click the link "Raw" inside that page, which points to the true script:
https://raw.githubusercontent.com/xiaoxiaoflood/firefox-scripts/master/chrome/extensionOptionsMenu.uc.js


> rebuild_userChrome.uc.js.txt

This is also wrong. The file extension must ends with .uc.js.

If in doubt, you should download the scripts using links provided in [readme](https://github.com/xiaoxiaoflood/firefox-scripts#readme).

**Comment by VLM-TechEd** [comment]
MORE: I closed Firefox, removed the two .css files, and relaunched Firefox. No change.

**Comment by xiaoxiaoflood** [comment]
> removed the two .css files

.css files are not related. Please read my previous comment.

**Comment by VLM-TechEd** [comment]
Okay, I re-downloaded everything. I now have the following.

In Program Files\Mozilla Firefox: the folder fx-folder, which contains the folder "defaults" and the file config.js. "defaults" contains the subfolder "pref", which contains the file config-prefs.js .

In chrome:

- the folder utils, which contains the subfolder utils, which contains 7 items beginning with boot.jsm and ending with xPref.jsm . 

- The following 4 files:

extensionOptionsMenu.uc.js
extensionOptionsMenu.uc.js.html (is this needed?)
rebuild_userChrome.uc.js
rebuild_userChrome.uc.js.txt (which I believe I can delete, correct?)

I created the two .js files manually by copying all the code into blank files using NPP. 

Still, nothing seems to work. One thing I don't see anywhere is an item called userChromeJS.extension .

**Comment by VLM-TechEd** [comment]
I just saw your last response, thank you. Our messages have overlapped. I did read your prior response, and per my last response, I have attempted to follow it perfectly. But apparently I have not succeeded.

**Comment by xiaoxiaoflood** [comment]
> the folder fx-folder

Nowhere it was said to create a folder `fx-folder`.

Just do exactly as it was done in the video I uploaded. And download the scripts using the links in [readme](https://github.com/xiaoxiaoflood/firefox-scripts#readme) instead of browsing the page here and there.

**Comment by VLM-TechEd** [comment]
Thank you for writing to me privately.

 

I must begin by saying that the video is almost completely useless to me. The combination of poor video quality and poor eyesight makes this so. This is why I relied entirely on the written instructions until now. Nevertheless, at your suggestion, I am trying to watch and follow the video.

 

When I click on that first link in “Download this zip file <https://raw.githubusercontent.com/xiaoxiaoflood/firefox-scripts/master/fx-folder.zip>  and extract its content to Firefox installation folder (usually C:\Program Files\Mozilla Firefox)”, I get fx-folder.zip. When I then use 7zip to extract the files, I put them into c:\Program Files\Mozilla Firefox\fx-folder. 7Zip breaks the destination into two parts, the path and the final folder. May I assume that the “fx-folder” portion is incorrect?

 

Also, when I watch the video it appears to me that you extract the files not to the Program Files location, but to a place somewhere in %appdata%. I cannot read the full path. 

 

I suspect that clarifying this may clean up the entire situation here. Would you be willing to clarify where this extracted content is supposed to go, perhaps by providing the path on your system?

 

Thank you kindly.

**Comment by VLM-TechEd** [comment]
I must begin by saying that the video is almost completely useless to me. The combination of poor video quality and poor eyesight makes this so. This is why I relied entirely on the written instructions until now. Nevertheless, at your suggestion, I am trying to watch and follow the video.

When I click on that first link in “Download this zip file and extract its content to Firefox installation folder (usually C:\Program Files\Mozilla Firefox)”, I get fx-folder.zip. When I then use 7zip to extract the files, I put them into c:\Program Files\Mozilla Firefox\fx-folder. 7Zip breaks the destination into two parts, the path and the final folder. May I assume that the “fx-folder” portion is incorrect?

Also, when I watch the video it appears to me that you extract the files not to the Program Files location, but to a place somewhere in %appdata%. I cannot read the full path. 

I suspect that clarifying this may clean up the entire situation here. Would you be willing to clarify where this extracted content is supposed to go, perhaps by providing the path on your system?

**Comment by etjim** [comment]
Open fx-folder,copy all file and folder to the Firefox's install folder.

**Comment by xiaoxiaoflood** [comment]
> poor video quality

The video was recorded in real resolution, so good quality, but unfortunately YouTube reduced it to 720p. 🤷‍♂️
I didn't recorded in fullscreen exactly by thinking of improving quality, because my screen resolution is 2560×1080, so things would be small and hard to see on YouTube player.

> When I then use 7zip to extract the files, I put them into c:\Program Files\Mozilla Firefox\fx-folder. 7Zip breaks the destination into two parts, the path and the final folder. May I assume that the “fx-folder” portion is incorrect?

Yes. I don't know if you changed anything in 7-zip, but the Extract button **doesn't** create a subfolder with the name of the compressed file (as shown in the video).

> Also, when I watch the video it appears to me that you extract the files not to the Program Files location, but to a place somewhere in %appdata%. I cannot read the full path.

As said in instructions, files in `fx-folder` must be extracted in... Firefox folder (where firefox.exe is). In Windows, the path **usually** is `C:\Program Files\Mozilla Firefox`, but can be anything. In the video I was using a fresh new profile in a fresh new Firefox *installation*, all temporary, so everything was in Temp folder.

In the video I pointed the cursor to show that, after extraction, the file `config.js` will be between `application.ini` and `crashreporter.exe` (suposing the default sorting - alphabetically).

**Comment by VLM-TechEd** [comment]
Thank you for staying with this conversation. I apologize for disappearing briefly; I was called away.

The config.js file is where you say it should be, between application.ini and crashreporter.exe (using default alpha sorting). 

The utils folder is inside the chrome folder. Inside the utils folder, I see another utils folder, and inside that, I see 7 items beginning with boot.jsm and ending with xPref.jsm, again using default alpha sort order. 

Finally, in the chrome folder I have placed 

extensionOptionsMenu.uc.js
rebuild_userChrome.uc.js
userChrome.css (for multirow tabs, not related to your code)
userContent.css (presently empty, not related to your code)

Can you identify anything here that seems incorrect or is missing? Thank you.

**Comment by xiaoxiaoflood** [comment]
> Inside the utils folder, I see another utils folder

This is wrong. There's only one utils folder. For instance, the path of xPref.jsm must be something like ...\chrome\utils\xPref.jsm. No double utils, only one.

**Comment by VLM-TechEd** [comment]
I fixed the utils folder and restarted Firefox. Still, I don't see Extension Options in the Tools menu, and TMP's xpi (re-downloaded) is rejected. As far as I can determine, I have now followed all instructions exactly. Is there some about:config setting that I should check?

**Comment by xiaoxiaoflood** [comment]
> I don't see Extension Options in the Tools menu

Extensions Options Menu is activated by a button that is added to navigation bar, next to buttons of other extensions, back, next, reload buttons, address bar... "Tools menu" is something different, not related to EOM. This is Tools menu:
![image](https://user-images.githubusercontent.com/25161346/134559301-0885044c-d230-41d5-9bdc-efe57a69b4d4.png)


> Is there some about:config setting that I should check?

I don't think so.

**Comment by VLM-TechEd** [comment]
Thank you. I was looking for it on the Tools menu, because that's where I remember it from XUL times. I am happy to report that I deleted, then re-downloaded and reinstalled everything, and now everything is working perfectly.

One "famous last question": on your scripts page (https://github.com/xiaoxiaoflood/firefox-scripts/tree/master/chrome), I notice that clicking on any script takes one to the actual script, not to a downloadable copy. Thus, I have copied the scripts desired and made each of them into a file named as listed on the scripts page. Is this what is intended? (I'm new at this, so I apologize for such a newbie question.

**Comment by xiaoxiaoflood** [comment]
No. As already said in https://github.com/xiaoxiaoflood/firefox-scripts/issues/96#issuecomment-922046111 and https://github.com/xiaoxiaoflood/firefox-scripts/issues/96#issuecomment-922076763, you should use links from readme and not to navigate between pages unless you're sure what are you doing (which is not the case).

I guess every problem we had here was by nor properly read and following readme. Extension Options Menu has a screenshot showing that it's a button in navbar, nothing related to Tools menu. From readme:
![image](https://user-images.githubusercontent.com/25161346/134565131-85d4303c-1722-49cd-9dca-c4201d93f6af.png)

**Comment by 117649** [comment]
>  clicking on any script takes one to the actual script, not to a downloadable copy. Thus, I have copied the scripts desired and made each of them into a file named as listed on the scripts page. Is this what is intended? 

Yes, this how Github works.

You can click **Raw** to get the file in plain text and save it use **Save Page as** function of the browser.

**Comment by VLM-TechEd** [comment]
Raw, then Save Page as. It takes a bit of time to learn how to use GitHub most effectively. 

Thanks for all your most patient help. Case closed.
