### ISSUE TITLE
BootstrapLoader enabled corrupts search engines list

### ISSUE THREAD

**Issue by gelirhil** [xiaoxiaoflood/firefox-scripts#98]
If one of Firefox built-in search engines (bing, google, duck-duck-go etc.) was used as default search engine after restarting Firefox with bootstrapLoader enabled (even without any legacy extensions installed) only country default search engine is available in search engine list. Restoring default engines list works only up to next browser restart.

For example:
1. Before bootstrapLoader enabled Google was used as default search engine.
2. After browser restart with bootstrapLoader enabled only Yandex (because of browser.search.region=RU in my case) was shown in search engines list and automatically became the default search engine.
3. "Restore default search engines" button in the Setting>Search brings all built-in engines list back. I can choose Google as default search engine and it works properly.
4. After next browser restart again only Yandex is in the list and used as default engine again.
5. browser.search.region=EN changes Yandex to Bing, all other behavior is the same.
6. If non-built-in engine was chosen as default no built-in engines are in the list (even country default) after restart.
7. Disabling bootstrapLoader restores correct behavior.

Windows 10 Home 21H1 64-bit
Firefox Nightly 94.0a1 (2021-09-25) (64-bit)

**Comment by etjim** [comment]
Suggest use userChromeJS instead install bootstrapLoader.xpi。

**Comment by xiaoxiaoflood** [comment]
Thanks for reporting. This should be fixed now.

**Comment by gelirhil** [comment]
A can confirm that everything now works well.
